; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
Vs_BattlefieldTypical:	.include "PRG/levels/2PVs/Typical"
Vs_Unused:		.include "PRG/levels/2PVs/Unused"
Vs_BattlefieldLadders:	.include "PRG/levels/2PVs/Ladders"
Vs_BattlefieldFountain:	.include "PRG/levels/2PVs/Fountain"
