BonusLayout_Typical:	.include "PRG/levels/Bonus/Typical"
BonusLayout_NoTable:	.include "PRG/levels/Bonus/NoTable"
BonusLayout_BlueBox:	.include "PRG/levels/Bonus/BlueBox"
BonusLayout_Empty1:	.include "PRG/levels/Bonus/Empty1"
BonusLayout_Empty2:	.include "PRG/levels/Bonus/Empty2"
