	.byte $01	; Unknown purpose

	.byte OBJ_CFIRE_GOOMBAPIPE_R, $19, $13
	.byte OBJ_GOOMBA, $20, $18
	.byte OBJ_CFIRE_GOOMBAPIPE_R, $2B, $13
	.byte OBJ_PARAGOOMBA, $39, $15
	.byte OBJ_GREENPIRANHA_FIRE, $4A, $11
	.byte OBJ_GOOMBA, $53, $17
	.byte OBJ_GOOMBA, $55, $10
	.byte OBJ_PARAGOOMBA, $61, $14
	.byte OBJ_GOOMBA, $6B, $16
	.byte OBJ_GOOMBA, $6C, $17
	.byte OBJ_GREENPIRANHA_FIRE, $6E, $16
	.byte OBJ_GOOMBA, $7E, $18
	.byte OBJ_GREENPIRANHA_FIRE, $81, $17
	.byte OBJ_CFIRE_GOOMBAPIPE_R, $8B, $14
	.byte OBJ_PARAGOOMBAWITHMICROS, $9D, $19
	.byte OBJ_ENDLEVELCARD, $A8, $15
	.byte $FF	; Terminator
