	.byte $01	; Unknown purpose

	.byte OBJ_AUTOSCROLL, $00, $00
	.byte OBJ_BONUSCONTROLLER, $01, $2C
	.byte OBJ_WOODENPLATFORM, $17, $14
	.byte OBJ_WOODENPLATFORM, $23, $16
	.byte OBJ_WOODENPLATFORM, $25, $13
	.byte OBJ_WOODENPLATFORM, $27, $19
	.byte OBJ_WOODENPLATFORM, $2F, $15
	.byte OBJ_REDTROOPA, $43, $15
	.byte OBJ_WOODENPLATFORM, $44, $18
	.byte OBJ_WOODENPLATFORM, $4B, $14
	.byte OBJ_WOODENPLATFORM, $56, $16
	.byte OBJ_WOODENPLATFORM, $58, $15
	.byte OBJ_WOODENPLATFORM, $61, $13
	.byte OBJ_WOODENPLATFORM, $6D, $18
	.byte OBJ_WOODENPLATFORM, $6F, $15
	.byte OBJ_WOODENPLATFORM, $70, $1A
	.byte OBJ_FLYINGREDPARATROOPA, $75, $13
	.byte OBJ_REDTROOPA, $7C, $16
	.byte $FF	; Terminator
