	.byte $01	; Unknown purpose

	.byte OBJ_BUZZYBEATLE, $0E, $0F
	.byte OBJ_BUZZYBEATLE, $11, $12
	.byte OBJ_BUZZYBEATLE, $13, $14
	.byte OBJ_BUZZYBEATLE, $15, $16
	.byte OBJ_REDPIRANHA_FLIPPED, $27, $10
	.byte OBJ_BUZZYBEATLE, $2C, $12
	.byte OBJ_GREENPIRANHA, $2D, $16
	.byte OBJ_GREENTROOPA, $48, $09
	.byte OBJ_GREENTROOPA, $4A, $0A
	.byte OBJ_GREENTROOPA, $54, $09
	.byte OBJ_GREENTROOPA, $6C, $0A
	.byte OBJ_VENUSFIRETRAP, $75, $15
	.byte OBJ_REDPIRANHA_FLIPPED, $7D, $14
	.byte $FF	; Terminator
