	.byte $01	; Unknown purpose

	.byte OBJ_REDTROOPA, $13, $12
	.byte OBJ_REDTROOPA, $1A, $18
	.byte OBJ_WOODENPLATFORMFALL, $21, $13
	.byte OBJ_FLYINGREDPARATROOPA, $30, $11
	.byte OBJ_GREENTROOPA, $36, $18
	.byte OBJ_WOODENPLATUNSTABLE, $4D, $18
	.byte OBJ_FLYINGREDPARATROOPA, $5C, $0D
	.byte OBJ_OSCILLATING_HS, $74, $14
	.byte OBJ_WOODENPLATUNSTABLE, $78, $12
	.byte OBJ_FLYINGREDPARATROOPA, $82, $15
	.byte OBJ_ENDLEVELCARD, $98, $15
	.byte OBJ_GREENTROOPA, $98, $18
	.byte $FF	; Terminator
