	.byte $01	; Unknown purpose

	.byte OBJ_BONUSCONTROLLER, $00, $1E
	.byte OBJ_GOOMBA, $0F, $15
	.byte OBJ_GREENPIRANHA_FIRE, $13, $19
	.byte OBJ_VENUSFIRETRAP, $26, $19
	.byte OBJ_GREENCHEEP, $38, $17
	.byte OBJ_WOODENPLAT_RIDER, $33, $14
	.byte OBJ_FLYINGGREENPARATROOPA, $39, $13
	.byte OBJ_GREENCHEEP, $48, $18
	.byte OBJ_GREENCHEEP, $55, $17
	.byte OBJ_GREENCHEEP, $5F, $18
	.byte OBJ_GREENCHEEP, $67, $17
	.byte OBJ_FLYINGGREENPARATROOPA, $60, $13
	.byte OBJ_FLYINGGREENPARATROOPA, $69, $12
	.byte $FF	; Terminator
