	.byte $00	; Unknown purpose

	.byte OBJ_PARAGOOMBA, $11, $17
	.byte OBJ_REDTROOPA, $14, $16
	.byte OBJ_GREENCHEEP, $16, $0A
	.byte OBJ_REDTROOPA, $1A, $16
	.byte OBJ_REDTROOPA, $23, $17
	.byte OBJ_BOOMERANGBRO, $30, $18
	.byte OBJ_PARATROOPAGREENHOP, $3A, $19
	.byte OBJ_REDTROOPA, $44, $17
	.byte OBJ_BOOMERANGBRO, $4E, $15
	.byte OBJ_FLYINGREDPARATROOPA, $55, $04
	.byte OBJ_FLYINGREDPARATROOPA, $58, $04
	.byte OBJ_GREENPIRANHA_FIRE, $5E, $15
	.byte OBJ_BOOMERANGBRO, $6B, $15
	.byte OBJ_BOOMERANGBRO, $95, $18
	.byte OBJ_ENDLEVELCARD, $98, $15
	.byte $FF	; Terminator
