; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $00	; Unknown purpose

	.byte OBJ_AUTOSCROLL, $04, $31
	.byte OBJ_BOO, $0C, $11
	.byte OBJ_BOO, $1E, $11
	.byte $FF	; Terminator
