	.byte $01	; Unknown purpose

	.byte OBJ_WATERCURRENTUPWARD, $14, $09
	.byte OBJ_BLOOPER, $1D, $06
	.byte OBJ_WATERCURRENTUPWARD, $24, $09
	.byte OBJ_BLOOPER, $30, $11
	.byte OBJ_WATERCURRENTDOWNARD, $33, $0C
	.byte OBJ_LAVALOTUS, $3A, $18
	.byte OBJ_LAVALOTUS, $4E, $18
	.byte OBJ_WATERCURRENTDOWNARD, $4E, $0C
	.byte OBJ_BLOOPERWITHKIDS, $67, $0A
	.byte OBJ_LAVALOTUS, $70, $18
	.byte OBJ_BLOOPER, $7B, $05
	.byte OBJ_WATERCURRENTUPWARD, $7D, $12
	.byte $FF	; Terminator
