	.byte $01	; Unknown purpose

	.byte OBJ_AUTOSCROLL, $00, $60
	.byte OBJ_CHARGINGCHEEPCHEEP, $00, $19
	.byte OBJ_WOODENPLATFORMFALL, $0B, $11
	.byte OBJ_WOODENPLATFORMFALL, $0F, $17
	.byte OBJ_WOODENPLATUNSTABLE, $1B, $15
	.byte OBJ_FLYINGREDPARATROOPA, $2F, $13
	.byte OBJ_CHEEPCHEEPHOPPER, $37, $19
	.byte OBJ_CHEEPCHEEPHOPPER, $3C, $19
	.byte OBJ_CHEEPCHEEPHOPPER, $4A, $19
	.byte OBJ_CHEEPCHEEPHOPPER, $4E, $19
	.byte OBJ_CHEEPCHEEPHOPPER, $5C, $19
	.byte OBJ_CHEEPCHEEPHOPPER, $5F, $19
	.byte OBJ_WOODENPLATUNSTABLE, $52, $15
	.byte OBJ_FLYINGREDPARATROOPA, $6B, $10
	.byte OBJ_CHEEPCHEEPHOPPER, $6A, $19
	.byte OBJ_CHEEPCHEEPHOPPER, $6F, $19
	.byte OBJ_GREENPIRANHA_FIRE, $7B, $13
	.byte $FF	; Terminator
