	.byte $01	; Unknown purpose

	.byte OBJ_GREENCHEEP, $0D, $12
	.byte OBJ_BIGBERTHABIRTHER, $16, $15
	.byte OBJ_WATERCURRENTUPWARD, $1E, $17
	.byte OBJ_BLOOPER, $24, $11
	.byte OBJ_GREENCHEEP, $2F, $14
	.byte OBJ_GREENCHEEP, $31, $0C
	.byte OBJ_WATERCURRENTDOWNARD, $36, $0D
	.byte OBJ_WATERCURRENTUPWARD, $48, $18
	.byte OBJ_GREENCHEEP, $49, $0D
	.byte OBJ_GREENCHEEP, $5D, $0D
	.byte OBJ_WATERCURRENTDOWNARD, $5E, $12
	.byte OBJ_BLOOPERWITHKIDS, $6C, $10
	.byte OBJ_BIGBERTHABIRTHER, $75, $15
	.byte OBJ_GREENCHEEP, $79, $0F
	.byte $FF	; Terminator
