	.byte $01	; Unknown purpose

	.byte OBJ_AUTOSCROLL, $00, $00
	.byte OBJ_TWIRLINGPERIODIC, $1D, $14
	.byte OBJ_REDTROOPA, $29, $12
	.byte OBJ_REDTROOPA, $3B, $12
	.byte OBJ_REDTROOPA, $3C, $18
	.byte OBJ_FLYINGREDPARATROOPA, $44, $14
	.byte OBJ_REDTROOPA, $54, $14
	.byte OBJ_PARATROOPAGREENHOP, $6E, $14
	.byte OBJ_FLYINGREDPARATROOPA, $76, $12
	.byte OBJ_TWIRLINGPERIODIC, $7A, $13
	.byte OBJ_AUTOSCROLL, $00, $00
	.byte $FF	; Terminator
