	.byte $01	; Unknown purpose

	.byte OBJ_PARATROOPAGREENHOP, $12, $07
	.byte OBJ_GREENPIRANHA_FLIPPED, $16, $08
	.byte OBJ_CFIRE_BULLETBILL, $20, $09
	.byte OBJ_PARAGOOMBAWITHMICROS, $22, $04
	.byte OBJ_BOBOMB, $2D, $0A
	.byte OBJ_BOBOMB, $33, $0A
	.byte OBJ_GREENCHEEP, $36, $18
	.byte OBJ_CFIRE_BULLETBILL, $3A, $0A
	.byte OBJ_BOBOMB, $3D, $0A
	.byte OBJ_BOBOMB, $46, $06
	.byte OBJ_CFIRE_BULLETBILL, $46, $0A
	.byte OBJ_BOBOMB, $4E, $04
	.byte OBJ_BOBOMB, $56, $0A
	.byte OBJ_BOBOMB, $5A, $0A
	.byte OBJ_GREENCHEEP, $5B, $15
	.byte OBJ_BOBOMB, $69, $0A
	.byte OBJ_GREENCHEEP, $6D, $14
	.byte OBJ_GREENTROOPA, $6F, $0A
	.byte OBJ_PARATROOPAGREENHOP, $7A, $0A
	.byte OBJ_PARATROOPAGREENHOP, $7E, $05
	.byte OBJ_GREENCHEEP, $83, $18
	.byte OBJ_GREENCHEEP, $8A, $14
	.byte $FF	; Terminator
