; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $00	; Unknown purpose

	.byte OBJ_GREENCHEEP, $21, $17
	.byte OBJ_GREENCHEEP, $3A, $17
	.byte OBJ_GREENCHEEP, $4C, $17
	.byte $FF	; Terminator
