	.byte $01	; Unknown purpose

	.byte OBJ_BIGREDPIRANHA, $0C, $16
	.byte OBJ_BIGGOOMBA, $10, $17
	.byte OBJ_BIGREDTROOPA, $18, $15
	.byte OBJ_VENUSFIRETRAP, $26, $07
	.byte OBJ_BIGGREENHOPPER, $30, $17
	.byte OBJ_BIGGOOMBA, $42, $0F
	.byte OBJ_BIGGREENHOPPER, $46, $11
	.byte OBJ_BIGREDTROOPA, $58, $13
	.byte OBJ_BIGREDTROOPA, $5F, $15
	.byte OBJ_BIGREDTROOPA, $64, $13
	.byte OBJ_VENUSFIRETRAP, $72, $15
	.byte OBJ_BIGGREENTROOPA, $7A, $17
	.byte $FF	; Terminator
