	.byte $01	; Unknown purpose

	.byte OBJ_AUTOSCROLL, $00, $52
	.byte OBJ_BONUSCONTROLLER, $01, $18
	.byte OBJ_BIGREDTROOPA, $10, $14
	.byte OBJ_CHARGINGCHEEPCHEEP, $12, $19
	.byte OBJ_BIGREDTROOPA, $16, $15
	.byte OBJ_BIGREDPIRANHA, $1B, $16
	.byte OBJ_VENUSFIRETRAP, $2E, $16
	.byte OBJ_VENUSFIRETRAP, $3C, $14
	.byte OBJ_CANCELEVENT, $48, $19
	.byte OBJ_BIGREDPIRANHA, $50, $14
	.byte OBJ_CHEEPCHEEPBEGIN, $5C, $19
	.byte OBJ_BIGREDPIRANHA, $63, $16
	.byte OBJ_CHEEPCHEEPBEGIN, $65, $19
	.byte OBJ_CANCELEVENT, $7C, $19
	.byte $FF	; Terminator
