; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $01	; Unknown purpose

	.byte OBJ_HEAVYBRO, $11, $17
	.byte OBJ_HEAVYBRO, $25, $17
	.byte $FF	; Terminator
