	.byte $01	; Unknown purpose

	.byte OBJ_BIGGREENTROOPA, $10, $13
	.byte OBJ_BIGGREENHOPPER, $15, $0F
	.byte OBJ_BIGGREENHOPPER, $1E, $17
	.byte OBJ_BIGREDPIRANHA, $22, $15
	.byte OBJ_CFIRE_BULLETBILL, $2C, $17
	.byte OBJ_CFIRE_MISSILEBILL, $33, $16
	.byte OBJ_CFIRE_BULLETBILL, $3A, $15
	.byte OBJ_CFIRE_MISSILEBILL, $42, $17
	.byte OBJ_BIGREDPIRANHA, $47, $18
	.byte OBJ_CFIRE_BULLETBILL, $55, $17
	.byte OBJ_CFIRE_BULLETBILL, $56, $16
	.byte OBJ_CFIRE_BULLETBILL, $5D, $18
	.byte OBJ_CFIRE_MISSILEBILL, $5C, $13
	.byte OBJ_REDPIRANHA, $51, $16
	.byte OBJ_BIGREDPIRANHA, $60, $15
	.byte OBJ_CFIRE_MISSILEBILL, $66, $14
	.byte OBJ_CFIRE_MISSILEBILL, $6A, $17
	.byte OBJ_BIGREDPIRANHA, $73, $15
	.byte OBJ_CFIRE_BULLETBILL, $79, $14
	.byte $FF	; Terminator
