	.byte $01	; Unknown purpose

	.byte OBJ_BIGGREENTROOPA, $18, $14
	.byte OBJ_BIGGREENTROOPA, $16, $18
	.byte OBJ_BIGGREENHOPPER, $11, $18
	.byte OBJ_BIGGREENPIRANHA, $26, $16
	.byte OBJ_BIGGREENTROOPA, $2D, $13
	.byte OBJ_BIGGOOMBA, $30, $18
	.byte OBJ_BIGGOOMBA, $32, $18
	.byte OBJ_BIGGREENHOPPER, $42, $18
	.byte OBJ_BIGGREENTROOPA, $4B, $18
	.byte OBJ_BIGGOOMBA, $4A, $14
	.byte OBJ_BIGGOOMBA, $54, $18
	.byte OBJ_BIGGREENTROOPA, $5C, $18
	.byte OBJ_BIGGREENPIRANHA, $56, $17
	.byte OBJ_BIGGREENPIRANHA, $5E, $16
	.byte OBJ_BIGREDTROOPA, $69, $18
	.byte OBJ_BIGREDTROOPA, $6D, $14
	.byte OBJ_BIGGREENHOPPER, $78, $15
	.byte OBJ_BIGGREENPIRANHA, $78, $17
	.byte OBJ_BIGREDTROOPA, $80, $15
	.byte OBJ_BIGGREENTROOPA, $81, $12
	.byte OBJ_BIGGREENHOPPER, $8C, $12
	.byte OBJ_BIGGREENHOPPER, $9E, $18
	.byte OBJ_ENDLEVELCARD, $A8, $15
	.byte $FF	; Terminator
