; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $01	; Unknown purpose

	.byte OBJ_DRYBONES, $08, $0A
	.byte OBJ_DRYBONES, $14, $0F
	.byte OBJ_BOO, $1D, $0A
	.byte OBJ_DRYBONES, $23, $0F
	.byte $FF	; Terminator
