; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $01	; Unknown purpose

	.byte OBJ_TREASURESET, $32, $0D
	.byte OBJ_TREASUREBOX, $33, $0F
	.byte OBJ_TREASUREBOXAPPEAR, $34, $0F
	.byte $FF	; Terminator
