	.byte $01	; Unknown purpose

	.byte OBJ_GOOMBA, $2E, $13
	.byte OBJ_GOOMBA, $30, $15
	.byte OBJ_GOOMBA, $31, $16
	.byte OBJ_GOOMBA, $42, $16
	.byte OBJ_GOOMBA, $43, $17
	.byte OBJ_PARATROOPAGREENHOP, $60, $16
	.byte OBJ_GREENCHEEP, $84, $18
	.byte OBJ_BUSTERBEATLE, $95, $14
	.byte OBJ_GREENPIRANHA_FLIPPED, $99, $12
	.byte OBJ_GREENPIRANHA_FLIPPED, $9D, $12
	.byte OBJ_GREENPIRANHA_FIREC, $A8, $16
	.byte OBJ_REDPIRANHA_FLIPPED, $AE, $16
	.byte OBJ_BUSTERBEATLE, $AA, $19
	.byte OBJ_VENUSFIRETRAP, $B4, $17
	.byte OBJ_BUSTERBEATLE, $C4, $15
	.byte OBJ_BUSTERBEATLE, $CF, $14
	.byte OBJ_BUSTERBEATLE, $D2, $19
	.byte OBJ_REDPIRANHA_FLIPPED, $D7, $15
	.byte OBJ_REDPIRANHA_FLIPPED, $E0, $15
	.byte OBJ_BUSTERBEATLE, $E0, $18
	.byte OBJ_BUSTERBEATLE, $EA, $18
	.byte $FF	; Terminator
