; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $01	; Unknown purpose

	.byte OBJ_GREENTROOPA, $0F, $10
	.byte OBJ_GREENTROOPA, $07, $10
	.byte OBJ_GREENTROOPA, $0E, $20
	.byte $FF	; Terminator
