	.byte $01	; Unknown purpose

	.byte OBJ_TWIRLINGPLATCWNS, $06, $12
	.byte OBJ_TWIRLINGPLATCWNS, $12, $15
	.byte OBJ_TWIRLINGPLATCWNS, $1C, $17
	.byte OBJ_TILTINGPLATFORM, $28, $13
	.byte OBJ_TWIRLINGPLATCW, $2F, $15
	.byte OBJ_TWIRLINGPLATCWNS, $2F, $19
	.byte OBJ_TILTINGPLATFORM, $37, $17
	.byte OBJ_TWIRLINGPLATCWNS, $44, $17
	.byte OBJ_TWIRLINGPLATCWNS, $45, $05
	.byte OBJ_TILTINGPLATFORM, $5D, $13
	.byte OBJ_FLYINGREDPARATROOPA, $61, $11
	.byte OBJ_TWIRLINGPERIODIC, $65, $15
	.byte OBJ_TILTINGPLATFORM, $6C, $17
	.byte OBJ_TWIRLINGPERIODIC, $73, $19
	.byte OBJ_PARATROOPAGREENHOP, $7C, $16
	.byte $FF	; Terminator
