; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $01	; Unknown purpose

	.byte OBJ_LAKITU, $0F, $12
	.byte OBJ_ENDLEVELCARD, $18, $15
	.byte $FF	; Terminator
