	.byte $01	; Unknown purpose

	.byte OBJ_BONUSCONTROLLER, $00, $1C
	.byte OBJ_PARATROOPAGREENHOP, $12, $15
	.byte OBJ_PARATROOPAGREENHOP, $17, $15
	.byte OBJ_PARAGOOMBAWITHMICROS, $14, $17
	.byte OBJ_PARATROOPAGREENHOP, $2D, $16
	.byte OBJ_VENUSFIRETRAP_CEIL, $30, $11
	.byte OBJ_VENUSFIRETRAP, $37, $17
	.byte OBJ_PARAGOOMBAWITHMICROS, $4E, $17
	.byte OBJ_FIRECHOMP, $52, $13
	.byte OBJ_REDPIRANHA, $54, $17
	.byte OBJ_VENUSFIRETRAP_CEIL, $69, $10
	.byte OBJ_PARATROOPAGREENHOP, $70, $15
	.byte OBJ_PARAGOOMBAWITHMICROS, $78, $17
	.byte OBJ_ENDLEVELCARD, $98, $15
	.byte $FF	; Terminator
