; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $01	; Unknown purpose

	.byte OBJ_REDTROOPA, $12, $19
	.byte OBJ_LAKITU, $56, $12
	.byte OBJ_ENDLEVELCARD, $68, $15
	.byte $FF	; Terminator
