	.byte $01	; Unknown purpose

	.byte OBJ_AUTOSCROLL, $00, $20
	.byte OBJ_FLYINGREDPARATROOPA, $0A, $10
	.byte OBJ_OSCILLATING_V, $10, $11
	.byte OBJ_OSCILLATING_V, $14, $0D
	.byte OBJ_OSCILLATING_VS, $18, $08
	.byte OBJ_OSCILLATING_V, $1C, $06
	.byte OBJ_OSCILLATING_V, $2C, $11
	.byte OBJ_OSCILLATING_V, $33, $0C
	.byte OBJ_OSCILLATING_V, $37, $0A
	.byte OBJ_OSCILLATING_H, $4C, $13
	.byte OBJ_OSCILLATING_V, $4E, $0F
	.byte OBJ_FIRECHOMP, $56, $14
	.byte OBJ_OSCILLATING_H, $58, $07
	.byte OBJ_OSCILLATING_VS, $5D, $05
	.byte OBJ_OSCILLATING_V, $74, $11
	.byte OBJ_OSCILLATING_V, $7A, $0A
	.byte OBJ_FIRECHOMP, $7E, $14
	.byte OBJ_OSCILLATING_H, $90, $12
	.byte OBJ_OSCILLATING_HS, $95, $0E
	.byte OBJ_OSCILLATING_VS, $96, $0B
	.byte $FF	; Terminator
