	.byte $00	; Unknown purpose

	.byte OBJ_PODOBOO, $0D, $13
	.byte OBJ_THWOMP, $16, $12
	.byte OBJ_ROTODISCCCLOCKWISE, $11, $14
	.byte OBJ_ROTODISCCLOCKWISE, $23, $14
	.byte OBJ_ROTODISCCCLOCKWISE, $2A, $0F
	.byte OBJ_THWOMP, $32, $0D
	.byte OBJ_ROTODISCCLOCKWISE, $3B, $0F
	.byte OBJ_ROTODISCCLOCKWISE, $3B, $14
	.byte OBJ_BOO, $49, $11
	.byte OBJ_THWOMP, $4D, $0F
	.byte OBJ_ROTODISCCCLOCKWISE, $4C, $15
	.byte OBJ_THWOMP, $5B, $0F
	.byte OBJ_ROTODISCCCLOCKWISE, $5C, $17
	.byte OBJ_THWOMP, $70, $0F
	.byte $FF	; Terminator
