	.byte $01	; Unknown purpose

	.byte OBJ_AUTOSCROLL, $00, $02
	.byte OBJ_CLOUDPLATFORM, $0F, $18
	.byte OBJ_CLOUDPLATFORM, $14, $15
	.byte OBJ_CLOUDPLATFORM, $1C, $13
	.byte OBJ_CLOUDPLATFORM, $2A, $11
	.byte OBJ_CLOUDPLATFORM_FAST, $2C, $14
	.byte OBJ_CLOUDPLATFORM, $3A, $19
	.byte OBJ_REDTROOPA, $30, $16
	.byte OBJ_CLOUDPLATFORM, $49, $15
	.byte OBJ_CLOUDPLATFORM, $4E, $0C
	.byte OBJ_CLOUDPLATFORM, $4D, $12
	.byte OBJ_CLOUDPLATFORM_FAST, $50, $10
	.byte OBJ_CLOUDPLATFORM, $53, $0D
	.byte OBJ_REDTROOPA, $5C, $07
	.byte OBJ_CLOUDPLATFORM, $67, $0A
	.byte OBJ_CLOUDPLATFORM, $69, $07
	.byte OBJ_CLOUDPLATFORM, $79, $11
	.byte OBJ_CLOUDPLATFORM, $78, $15
	.byte OBJ_CLOUDPLATFORM, $88, $16
	.byte $FF	; Terminator
