	.byte $01	; Unknown purpose

	.byte OBJ_TWIRLINGPLATCW, $12, $16
	.byte OBJ_TWIRLINGPLATCW, $19, $18
	.byte OBJ_GOOMBA, $1E, $12
	.byte OBJ_GOOMBA, $23, $12
	.byte OBJ_GOOMBA, $24, $12
	.byte OBJ_WOODENPLATUNSTABLE, $2E, $13
	.byte OBJ_OSCILLATING_HS, $3F, $19
	.byte OBJ_WOODENPLATFORMFALL, $46, $18
	.byte OBJ_WOODENPLATFORMFALL, $4D, $16
	.byte OBJ_TWIRLINGPLATCWNS, $62, $15
	.byte OBJ_TWIRLINGPLATCWNS, $6B, $16
	.byte OBJ_FIRECHOMP, $77, $10
	.byte OBJ_TWIRLINGPLATCWNS, $75, $16
	.byte OBJ_TWIRLINGPLATCWNS, $7E, $15
	.byte OBJ_TWIRLINGPLATCWNS, $87, $15
	.byte OBJ_TWIRLINGPLATCWNS, $90, $16
	.byte OBJ_ENDLEVELCARD, $A8, $15
	.byte $FF	; Terminator
