; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $01	; Unknown purpose

	.byte OBJ_SPIKE, $2B, $19
	.byte OBJ_ENDLEVELCARD, $38, $15
	.byte $FF	; Terminator
