; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $01	; Unknown purpose

	.byte OBJ_PARATROOPAGREENHOP, $06, $17
	.byte OBJ_ENDLEVELCARD, $28, $15
	.byte $FF	; Terminator
