; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $01	; Unknown purpose

	.byte OBJ_REDTROOPA, $26, $0D
	.byte OBJ_ENDLEVELCARD, $58, $15
	.byte $FF	; Terminator
