	.byte $01	; Unknown purpose

	.byte OBJ_GREENCHEEP, $0D, $16
	.byte OBJ_BLOOPERCHILDSHOOT, $17, $14
	.byte OBJ_WATERCURRENTDOWNARD, $1C, $14
	.byte OBJ_GREENPIRANHA_FLIPPED, $23, $04
	.byte OBJ_BIGBERTHABIRTHER, $24, $16
	.byte OBJ_WATERCURRENTUPWARD, $28, $17
	.byte OBJ_WATERCURRENTDOWNARD, $31, $16
	.byte OBJ_REDPIRANHA_FLIPPED, $33, $08
	.byte OBJ_GREENCHEEP, $44, $14
	.byte OBJ_BLOOPERCHILDSHOOT, $4E, $14
	.byte OBJ_WATERCURRENTUPWARD, $57, $18
	.byte OBJ_GREENCHEEP, $58, $14
	.byte OBJ_GREENPIRANHA, $65, $09
	.byte OBJ_WATERCURRENTDOWNARD, $65, $16
	.byte OBJ_GREENPIRANHA_FIRE, $6C, $08
	.byte OBJ_BIGBERTHABIRTHER, $6C, $13
	.byte $FF	; Terminator
