	.byte $00	; Unknown purpose

	.byte OBJ_ROTODISCDUAL, $08, $16
	.byte OBJ_ROTODISCCCLOCKWISE, $17, $14
	.byte OBJ_ROTODISCCCLOCKWISE, $1E, $15
	.byte OBJ_ROTODISCDUALOPPOSE2, $25, $0A
	.byte OBJ_ROTODISCCCLOCKWISE, $30, $12
	.byte $FF	; Terminator
