	.byte $01	; Unknown purpose

	.byte OBJ_BOO, $0E, $10
	.byte OBJ_THWOMPLEFTSLIDE, $15, $15
	.byte OBJ_THWOMPRIGHTSLIDE, $1C, $11
	.byte OBJ_THWOMPLEFTSLIDE, $2F, $15
	.byte OBJ_THWOMPRIGHTSLIDE, $34, $11
	.byte OBJ_ROTODISCDUALCCLOCK, $48, $17
	.byte OBJ_THWOMPRIGHTSLIDE, $4B, $11
	.byte OBJ_ROTODISCDUALCCLOCK, $57, $13
	.byte OBJ_BOO, $57, $16
	.byte OBJ_THWOMPRIGHTSLIDE, $61, $15
	.byte OBJ_THWOMPLEFTSLIDE, $77, $18
	.byte $FF	; Terminator
