	.byte $00	; Unknown purpose

	.byte OBJ_ROTODISCDUALCCLOCK, $13, $15
	.byte OBJ_ROTODISCDUAL, $1F, $15
	.byte OBJ_BOO, $26, $12
	.byte OBJ_BOO, $2D, $12
	.byte OBJ_BOOSTRETCH, $38, $17
	.byte OBJ_BOOSTRETCH, $3E, $15
	.byte OBJ_BOOSTRETCH_FLIP, $3E, $17
	.byte OBJ_BOO, $44, $16
	.byte OBJ_BOOSTRETCH, $4D, $15
	.byte OBJ_ROTODISCCLOCKWISE, $54, $15
	.byte OBJ_THWOMP, $5A, $10
	.byte OBJ_ROTODISCCCLOCKWISE, $64, $14
	.byte OBJ_ROTODISCDUALOPPOSE2, $7C, $16
	.byte OBJ_BOOSTRETCH, $7A, $15
	.byte OBJ_BOOSTRETCH, $81, $15
	.byte OBJ_BOOMBOOMJUMP, $AC, $37
	.byte $FF	; Terminator
