	.byte $01	; Unknown purpose

	.byte OBJ_FLYINGREDPARATROOPA, $09, $07
	.byte OBJ_GREENTROOPA, $02, $10
	.byte OBJ_GREENTROOPA, $04, $10
	.byte OBJ_REDPIRANHA, $0E, $27
	.byte OBJ_PIRANHASIDEWAYSRIGHT, $07, $2C
	.byte OBJ_PIRANHASIDEWAYSLEFT, $0E, $2F
	.byte OBJ_PIRANHASIDEWAYSLEFT, $0A, $33
	.byte OBJ_REDTROOPA, $01, $36
	.byte OBJ_FLYINGREDPARATROOPA, $04, $43
	.byte OBJ_REDTROOPA, $0C, $48
	.byte OBJ_REDTROOPA, $07, $57
	.byte OBJ_REDPIRANHA, $08, $5E
	.byte OBJ_PIRANHASIDEWAYSRIGHT, $02, $60
	.byte OBJ_PIRANHASIDEWAYSLEFT, $08, $60
	.byte OBJ_REDTROOPA, $03, $6D
	.byte $FF	; Terminator
