	.byte $00	; Unknown purpose

	.byte OBJ_BONUSCONTROLLER, $00, $2E
	.byte OBJ_NIPPERHOPPING, $0E, $0A
	.byte OBJ_NIPPER, $1D, $08
	.byte OBJ_NIPPER, $23, $06
	.byte OBJ_VENUSFIRETRAP, $24, $05
	.byte OBJ_WATERCURRENTDOWNARD, $2E, $13
	.byte OBJ_NIPPERHOPPING, $36, $02
	.byte OBJ_VENUSFIRETRAP, $3C, $07
	.byte OBJ_PARATROOPAGREENHOP, $49, $08
	.byte OBJ_NIPPERHOPPING, $55, $18
	.byte OBJ_NIPPERHOPPING, $58, $18
	.byte OBJ_VENUSFIRETRAP, $5A, $03
	.byte OBJ_VENUSFIRETRAP, $60, $09
	.byte OBJ_VENUSFIRETRAP, $64, $04
	.byte OBJ_GREENPIRANHA_FLIPPED, $66, $11
	.byte OBJ_VENUSFIRETRAP, $6A, $08
	.byte OBJ_REDPIRANHA, $6E, $07
	.byte OBJ_NIPPERHOPPING, $71, $04
	.byte OBJ_VENUSFIRETRAP, $72, $04
	.byte OBJ_VENUSFIRETRAP, $78, $07
	.byte $FF	; Terminator
