	.byte $01	; Unknown purpose

	.byte OBJ_GREENTROOPA, $13, $13
	.byte OBJ_GREENTROOPA, $17, $15
	.byte OBJ_GREENTROOPA, $1A, $16
	.byte OBJ_GREENTROOPA, $1E, $19
	.byte OBJ_GREENTROOPA, $33, $13
	.byte OBJ_GREENTROOPA, $37, $15
	.byte OBJ_PARATROOPAGREENHOP, $3C, $17
	.byte OBJ_PARATROOPAGREENHOP, $3F, $18
	.byte OBJ_SPINY, $51, $14
	.byte OBJ_SPINY, $57, $17
	.byte OBJ_SPINY, $59, $18
	.byte OBJ_VENUSFIRETRAP, $60, $19
	.byte OBJ_LAKITU, $65, $12
	.byte OBJ_CFIRE_GOOMBAPIPE_L, $92, $18
	.byte OBJ_CFIRE_GOOMBAPIPE_R, $94, $18
	.byte OBJ_PARATROOPAGREENHOP, $B3, $17
	.byte OBJ_PARATROOPAGREENHOP, $B7, $17
	.byte OBJ_ENDLEVELCARD, $C8, $15
	.byte $FF	; Terminator
