	.byte $01	; Unknown purpose

	.byte OBJ_AUTOSCROLL, $00, $0F
	.byte OBJ_GREENCHEEPBEGIN, $0F, $0F
	.byte OBJ_LAVALOTUS, $14, $18
	.byte OBJ_BIGBERTHABIRTHER, $2E, $13
	.byte OBJ_BLOOPERCHILDSHOOT, $36, $13
	.byte OBJ_CANCELEVENT, $3F, $0F
	.byte OBJ_BIGBERTHABIRTHER, $56, $0D
	.byte OBJ_BLOOPERCHILDSHOOT, $63, $0C
	.byte OBJ_BLOOPERCHILDSHOOT, $69, $10
	.byte OBJ_GREENCHEEPBEGIN, $6F, $0F
	.byte OBJ_LAVALOTUS, $7E, $18
	.byte OBJ_BIGBERTHABIRTHER, $8A, $13
	.byte OBJ_LAVALOTUS, $97, $15
	.byte $FF	; Terminator
