	.byte $01	; Unknown purpose

	.byte OBJ_PIRANHASIDEWAYSRIGHT, $0B, $0D
	.byte OBJ_PIRANHASIDEWAYSLEFT, $05, $0F
	.byte OBJ_GREENPIRANHA, $04, $42
	.byte OBJ_REDTROOPA, $05, $52
	.byte OBJ_PIRANHASIDEWAYSLEFT, $0B, $5B
	.byte OBJ_GREENPIRANHA, $04, $61
	.byte OBJ_GREENTROOPA, $0D, $67
	.byte OBJ_GREENTROOPA, $0F, $67
	.byte $FF	; Terminator
