; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $00	; Unknown purpose

	.byte OBJ_PSWITCHDOOR, $0C, $0B
	.byte OBJ_BOOMBOOMFLY, $6C, $17
	.byte $FF	; Terminator
