	.byte $01	; Unknown purpose

	.byte OBJ_GREENPIRANHA_FIRE, $16, $13
	.byte OBJ_GREENPIRANHA, $1C, $16
	.byte OBJ_GREENPIRANHA_FIRE, $20, $13
	.byte OBJ_GREENPIRANHA, $24, $12
	.byte OBJ_PARATROOPAGREENHOP, $33, $19
	.byte OBJ_CFIRE_BULLETBILL, $37, $16
	.byte OBJ_CFIRE_BULLETBILL, $37, $18
	.byte OBJ_CFIRE_BULLETBILL, $3C, $14
	.byte OBJ_CFIRE_BULLETBILL, $3C, $19
	.byte OBJ_CFIRE_BULLETBILL, $4F, $18
	.byte OBJ_CFIRE_BULLETBILL, $50, $13
	.byte OBJ_BOO, $51, $12
	.byte OBJ_REDTROOPA, $59, $16
	.byte OBJ_GREENPIRANHA_FIRE, $5F, $14
	.byte OBJ_PARATROOPAGREENHOP, $6A, $17
	.byte OBJ_CFIRE_BULLETBILL, $6B, $18
	.byte OBJ_FLYINGREDPARATROOPA, $6E, $14
	.byte OBJ_CFIRE_BULLETBILL, $72, $13
	.byte OBJ_CFIRE_BULLETBILL, $72, $16
	.byte OBJ_CFIRE_BULLETBILL, $7A, $15
	.byte OBJ_CFIRE_BULLETBILL, $7A, $18
	.byte OBJ_GREENTROOPA, $7F, $19
	.byte OBJ_REDPIRANHA, $91, $15
	.byte OBJ_ENDLEVELCARD, $A8, $15
	.byte $FF	; Terminator
