	.byte $01	; Unknown purpose

	.byte OBJ_ENEMYSUN, $02, $11
	.byte OBJ_PARAGOOMBAWITHMICROS, $2E, $05
	.byte OBJ_VENUSFIRETRAP, $3A, $0A
	.byte OBJ_VENUSFIRETRAP, $40, $0A
	.byte OBJ_VENUSFIRETRAP, $46, $0A
	.byte OBJ_VENUSFIRETRAP, $50, $0B
	.byte OBJ_VENUSFIRETRAP, $56, $0F
	.byte OBJ_VENUSFIRETRAP, $5C, $13
	.byte OBJ_VENUSFIRETRAP, $8D, $13
	.byte OBJ_CANCELEVENT, $92, $01
	.byte OBJ_VENUSFIRETRAP, $93, $0F
	.byte OBJ_VENUSFIRETRAP, $99, $0B
	.byte OBJ_FLYINGGREENPARATROOPA, $C1, $19
	.byte OBJ_ENDLEVELCARD, $E8, $15
	.byte $FF	; Terminator
