	.byte $00	; Unknown purpose

	.byte OBJ_ROTODISCCLOCKWISE, $11, $16
	.byte OBJ_ROTODISCDUALOPPOSE2, $1C, $16
	.byte OBJ_ROTODISCDUALCCLOCK, $28, $16
	.byte OBJ_DRYBONES, $31, $18
	.byte OBJ_ROTODISCCLOCKWISE, $35, $17
	.byte OBJ_THWOMPDIAGONALDL, $4C, $10
	.byte OBJ_THWOMPLEFTSLIDE, $50, $18
	.byte OBJ_THWOMP, $52, $10
	.byte OBJ_THWOMPDIAGONALDL, $5C, $10
	.byte OBJ_BOO, $83, $17
	.byte OBJ_DRYBONES, $87, $13
	.byte OBJ_THWOMP, $9A, $10
	.byte OBJ_ROTODISCDUALOPPOSE2, $A0, $15
	.byte OBJ_DRYBONES, $A8, $13
	.byte OBJ_PSWITCHDOOR, $AA, $13
	.byte OBJ_ROTODISCCCLOCKWISE, $B4, $17
	.byte OBJ_DRYBONES, $B9, $14
	.byte OBJ_BOOMBOOMJUMP, $EC, $38
	.byte $FF	; Terminator
