; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $01	; Unknown purpose

	.byte OBJ_BIGQBLOCK_HAMMER, $44, $09
	.byte OBJ_BIGQBLOCK_TANOOKI, $67, $14
	.byte $FF	; Terminator
