; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $01	; Unknown purpose

	.byte OBJ_BIGQBLOCK_3UP, $27, $14
	.byte OBJ_BIGQBLOCK_FROG, $37, $14
	.byte $FF	; Terminator
