; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $01	; Unknown purpose

	.byte OBJ_BIGQBLOCK_3UP, $35, $14
	.byte OBJ_BIGQBLOCK_TANOOKI, $57, $14
	.byte OBJ_BIGQBLOCK_HAMMER, $65, $06
	.byte $FF	; Terminator
