; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $01	; Unknown purpose

	.byte OBJ_BIGQBLOCK_TANOOKI, $18, $05
	.byte OBJ_BIGQBLOCK_3UP, $48, $05
	.byte $FF	; Terminator
