	.byte $00	; Unknown purpose

	.byte OBJ_CFIRE_LASER, $18, $14
	.byte OBJ_CFIRE_LASER, $1D, $14
	.byte OBJ_CFIRE_LASER, $22, $14
	.byte OBJ_INVISIBLELIFT, $31, $10
	.byte OBJ_HOTFOOT_SHY, $4E, $15
	.byte OBJ_ROTODISCCLOCKWISE, $55, $13
	.byte OBJ_ROTODISCCLOCKWISE, $58, $0D
	.byte OBJ_ROTODISCCLOCKWISE, $5B, $07
	.byte OBJ_PODOBOO, $6A, $09
	.byte OBJ_PODOBOO, $6E, $09
	.byte OBJ_PODOBOO, $74, $09
	.byte OBJ_PODOBOO, $7A, $09
	.byte OBJ_ROTODISCDUAL, $89, $12
	.byte OBJ_THWOMPLEFTSLIDE, $9A, $0F
	.byte OBJ_PODOBOO, $A1, $13
	.byte OBJ_ROTODISCCLOCKWISE, $A8, $18
	.byte OBJ_PODOBOO, $AA, $13
	.byte OBJ_PODOBOO, $AF, $13
	.byte OBJ_BOSS_BOWSER, $CC, $0B
	.byte OBJ_BOSS_BOWSER, $EC, $0B
	.byte $FF	; Terminator
