; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $01	; Unknown purpose

	.byte OBJ_ROTODISCCCLOCKWISE, $0D, $14
	.byte OBJ_ROTODISCCLOCKWISE, $13, $14
	.byte OBJ_ROTODISCCCLOCKWISE, $26, $16
	.byte OBJ_ROTODISCCLOCKWISE, $29, $16
	.byte $FF	; Terminator
