; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $01	; Unknown purpose

	.byte OBJ_GREENTROOPA, $14, $0F
	.byte OBJ_CFIRE_BULLETBILL, $5E, $0F
	.byte OBJ_AUTOSCROLL, $61, $00
	.byte $FF	; Terminator
