; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $01	; Unknown purpose

	.byte OBJ_WOODENPLATFORMFALL, $08, $15
	.byte OBJ_WOODENPLATFORMFALL, $38, $11
	.byte $FF	; Terminator
