; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $01	; Unknown purpose

	.byte OBJ_BUZZYBEATLE, $0B, $12
	.byte OBJ_BUZZYBEATLE, $0D, $12
	.byte OBJ_ENDLEVELCARD, $18, $15
	.byte $FF	; Terminator
