	.byte $01	; Unknown purpose

	.byte OBJ_GREENTROOPA, $38, $06
	.byte OBJ_REDPIRANHA_FLIPPED, $3C, $08
	.byte OBJ_REDPIRANHA_FLIPPED, $40, $06
	.byte OBJ_REDPIRANHA_FLIPPED, $46, $04
	.byte OBJ_REDPIRANHA_FLIPPED, $4A, $05
	.byte OBJ_REDPIRANHA_FLIPPED, $4C, $06
	.byte OBJ_REDPIRANHA_FLIPPED, $4E, $07
	.byte OBJ_ENDLEVELCARD, $88, $15
	.byte $FF	; Terminator
