	.byte $01	; Unknown purpose

	.byte OBJ_CFIRE_GOOMBAPIPE_L, $17, $14
	.byte OBJ_CFIRE_GOOMBAPIPE_R, $19, $14
	.byte OBJ_CFIRE_GOOMBAPIPE_L, $2C, $17
	.byte OBJ_GREENTROOPA, $33, $17
	.byte OBJ_GREENTROOPA, $3B, $18
	.byte OBJ_GREENTROOPA, $41, $17
	.byte OBJ_CFIRE_GOOMBAPIPE_R, $47, $17
	.byte OBJ_GREENPIRANHA, $6B, $16
	.byte OBJ_GREENPIRANHA, $70, $17
	.byte OBJ_ENDLEVELCARD, $88, $15
	.byte $FF	; Terminator
