	.byte $01	; Unknown purpose

	.byte OBJ_BUZZYBEATLE, $12, $0D
	.byte OBJ_BUZZYBEATLE, $16, $0D
	.byte OBJ_GREENPIRANHA, $19, $11
	.byte OBJ_GREENPIRANHA_FLIPPED, $26, $09
	.byte OBJ_GREENPIRANHA_FLIPPED, $2B, $05
	.byte OBJ_GREENPIRANHA, $2B, $0B
	.byte OBJ_BUZZYBEATLE, $28, $0C
	.byte OBJ_BUZZYBEATLE, $2A, $0C
	.byte OBJ_BUZZYBEATLE, $27, $09
	.byte OBJ_BUZZYBEATLE, $2D, $05
	.byte OBJ_GREENPIRANHA, $41, $07
	.byte OBJ_BUZZYBEATLE, $50, $0C
	.byte OBJ_GREENPIRANHA_FLIPPED, $54, $09
	.byte OBJ_BUZZYBEATLE, $68, $10
	.byte OBJ_GREENPIRANHA_FLIPPED, $6A, $0E
	.byte OBJ_BUZZYBEATLE, $6F, $10
	.byte OBJ_GREENPIRANHA, $70, $0F
	.byte OBJ_GREENPIRANHA_FLIPPED, $72, $0C
	.byte $FF	; Terminator
