	.byte $01	; Unknown purpose

	.byte OBJ_WOODENPLATFORMFALL, $09, $0E
	.byte OBJ_REDTROOPA, $1E, $06
	.byte OBJ_WOODENPLATFORMFALL, $11, $08
	.byte OBJ_WOODENPLATFORMFALL, $14, $10
	.byte OBJ_WOODENPLATFORMFALL, $27, $06
	.byte OBJ_WOODENPLATFORMFALL, $27, $13
	.byte OBJ_OSCILLATING_H, $3E, $08
	.byte OBJ_WOODENPLATFORMFALL, $31, $03
	.byte OBJ_OSCILLATING_V, $4A, $11
	.byte OBJ_REDTROOPA, $52, $0E
	.byte OBJ_WOODENPLATFORMFALL, $57, $0A
	.byte OBJ_WOODENPLATFORMFALL, $56, $18
	.byte OBJ_WOODENPLATFORMFALL, $5F, $14
	.byte OBJ_OSCILLATING_H, $7B, $11
	.byte OBJ_WOODENPLATFORMFALL, $78, $09
	.byte OBJ_WOODENPLATFORMFALL, $74, $18
	.byte OBJ_ENDLEVELCARD, $88, $15
	.byte $FF	; Terminator
