	.byte $01	; Unknown purpose

	.byte OBJ_AUTOSCROLL, $00, $54
	.byte OBJ_GREENCHEEP, $11, $16
	.byte OBJ_GREENCHEEP, $17, $14
	.byte OBJ_WATERCURRENTDOWNARD, $1A, $0E
	.byte OBJ_GREENCHEEP, $1C, $17
	.byte OBJ_BIGBERTHABIRTHER, $22, $15
	.byte OBJ_BLOOPERCHILDSHOOT, $29, $10
	.byte OBJ_GREENCHEEP, $2A, $14
	.byte OBJ_GREENCHEEP, $32, $16
	.byte OBJ_WATERCURRENTDOWNARD, $41, $0E
	.byte OBJ_WATERCURRENTDOWNARD, $43, $0F
	.byte OBJ_GREENCHEEP, $48, $16
	.byte OBJ_GREENCHEEP, $4C, $14
	.byte OBJ_GREENCHEEP, $50, $17
	.byte OBJ_SPAWN3ORANGECHEEPS, $57, $15
	.byte OBJ_GREENCHEEP, $60, $16
	.byte OBJ_WATERCURRENTDOWNARD, $65, $0E
	.byte OBJ_WATERCURRENTDOWNARD, $69, $0E
	.byte OBJ_SPAWN3ORANGECHEEPS, $72, $15
	.byte OBJ_BLOOPERCHILDSHOOT, $78, $12
	.byte $FF	; Terminator
