; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $01	; Unknown purpose

	.byte OBJ_AUTOSCROLL, $00, $11
	.byte OBJ_CLOUDSINBGBEGIN, $01, $03
	.byte OBJ_AIRSHIPPROP, $3E, $0B
	.byte $FF	; Terminator
