; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $00	; Unknown purpose

	.byte OBJ_THWOMP, $3E, $12
	.byte OBJ_ROTODISCCLOCKWISE, $45, $15
	.byte OBJ_THWOMP, $4B, $12
	.byte $FF	; Terminator
