; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $00	; Unknown purpose

	.byte OBJ_BOOMERANGBRO, $69, $18
	.byte OBJ_ENDLEVELCARD, $78, $15
	.byte $FF	; Terminator
