	.byte $01	; Unknown purpose

	.byte OBJ_BUZZYBEATLE, $10, $0F
	.byte OBJ_BUZZYBEATLE, $13, $12
	.byte OBJ_BUZZYBEATLE, $23, $0F
	.byte OBJ_BUZZYBEATLE, $25, $19
	.byte OBJ_REDPIRANHA, $31, $13
	.byte OBJ_BUZZYBEATLE, $32, $0A
	.byte OBJ_BUZZYBEATLE, $34, $19
	.byte OBJ_BUZZYBEATLE, $3B, $14
	.byte OBJ_BUZZYBEATLE, $40, $0F
	.byte OBJ_BUZZYBEATLE, $4B, $13
	.byte OBJ_BUZZYBEATLE, $4E, $16
	.byte OBJ_TWIRLINGBUZZY, $63, $0C
	.byte OBJ_BUZZYBEATLE, $67, $0F
	.byte OBJ_TWIRLINGBUZZY, $6E, $0C
	.byte OBJ_GREENPIRANHA, $72, $0F
	.byte $FF	; Terminator
