	.byte $01	; Unknown purpose

	.byte OBJ_ENEMYSUN, $02, $11
	.byte OBJ_GREENPIRANHA_FIRE, $1A, $1A
	.byte OBJ_FLYINGREDPARATROOPA, $1B, $12
	.byte OBJ_GREENPIRANHA_FIRE, $29, $19
	.byte OBJ_GREENPIRANHA_FIRE, $2C, $19
	.byte OBJ_GREENTROOPA, $37, $19
	.byte OBJ_TORNADO, $51, $12
	.byte OBJ_PARATROOPAGREENHOP, $7E, $16
	.byte OBJ_PARATROOPAGREENHOP, $9E, $16
	.byte OBJ_ENDLEVELCARD, $D8, $15
	.byte $FF	; Terminator
