	.byte $00	; Unknown purpose

	.byte OBJ_BIGQBLOCK_TANOOKI, $06, $14
	.byte OBJ_BIGQBLOCK_TANOOKI, $17, $11
	.byte OBJ_BIGQBLOCK_TANOOKI, $2A, $0A
	.byte OBJ_BIGQBLOCK_TANOOKI, $37, $14
	.byte OBJ_BIGQBLOCK_TANOOKI, $47, $14
	.byte OBJ_BIGQBLOCK_TANOOKI, $56, $11
	.byte OBJ_BIGQBLOCK_TANOOKI, $6A, $14
	.byte OBJ_BIGQBLOCK_TANOOKI, $73, $0A
	.byte $FF	; Terminator
