	.byte $01	; Unknown purpose

	.byte OBJ_AUTOSCROLL, $00, $53
	.byte OBJ_CHEEPCHEEPHOPPER, $11, $19
	.byte OBJ_CHEEPCHEEPHOPPER, $19, $19
	.byte OBJ_CHEEPCHEEPHOPPER, $23, $19
	.byte OBJ_FIRECHOMP, $40, $13
	.byte OBJ_FLYINGREDPARATROOPA, $4B, $12
	.byte OBJ_FIRESNAKE, $57, $10
	.byte OBJ_WOODENPLATUNSTABLE, $5D, $15
	.byte OBJ_FIRECHOMP, $6B, $11
	.byte OBJ_CHEEPCHEEPHOPPER, $6B, $19
	.byte OBJ_CHEEPCHEEPPOOL2POOL2, $76, $19
	.byte $FF	; Terminator
