	.byte $01	; Unknown purpose

	.byte OBJ_AUTOSCROLL, $00, $09
	.byte OBJ_GREENCHEEP, $12, $10
	.byte OBJ_WATERCURRENTDOWNARD, $18, $16
	.byte OBJ_GREENCHEEP, $1D, $17
	.byte OBJ_BLOOPERWITHKIDS, $1F, $11
	.byte OBJ_GREENCHEEP, $2D, $15
	.byte OBJ_SPAWN3ORANGECHEEPS, $34, $11
	.byte OBJ_BLOOPERWITHKIDS, $3B, $11
	.byte OBJ_SPAWN3ORANGECHEEPS, $3C, $0C
	.byte OBJ_REDTROOPA, $44, $09
	.byte OBJ_FLYINGREDPARATROOPA, $51, $03
	.byte OBJ_REDTROOPA, $56, $07
	.byte OBJ_GREENTROOPA, $58, $07
	.byte OBJ_REDTROOPA, $61, $09
	.byte OBJ_WATERCURRENTDOWNARD, $6C, $11
	.byte OBJ_WATERCURRENTDOWNARD, $72, $11
	.byte OBJ_GREENCHEEP, $77, $15
	.byte $FF	; Terminator
