	.byte $01	; Unknown purpose

	.byte OBJ_BUZZYBEATLE, $12, $13
	.byte OBJ_BUZZYBEATLE, $15, $10
	.byte OBJ_BUZZYBEATLE, $19, $10
	.byte OBJ_GREENPIRANHA_FIRE, $1F, $16
	.byte OBJ_REDPIRANHA_FLIPPED, $25, $0F
	.byte OBJ_REDPIRANHA_FLIPPED, $2C, $0C
	.byte OBJ_BUZZYBEATLE, $2B, $0F
	.byte OBJ_BUZZYBEATLE, $32, $12
	.byte OBJ_BUZZYBEATLE, $34, $14
	.byte OBJ_GREENPIRANHA_FIRE, $37, $18
	.byte OBJ_GREENTROOPA, $4C, $09
	.byte OBJ_GREENTROOPA, $50, $0B
	.byte OBJ_GREENTROOPA, $56, $09
	.byte OBJ_GREENTROOPA, $65, $0B
	.byte OBJ_GREENPIRANHA_FIRE, $64, $14
	.byte OBJ_REDPIRANHA, $66, $16
	.byte OBJ_REDPIRANHA, $6C, $17
	.byte OBJ_BUZZYBEATLE, $6A, $18
	.byte OBJ_REDPIRANHA, $71, $15
	.byte OBJ_BUZZYBEATLE, $76, $18
	.byte OBJ_GREENPIRANHA, $78, $17
	.byte OBJ_GREENPIRANHA_FLIPPED, $78, $13
	.byte $FF	; Terminator
