	.byte $00	; Unknown purpose

	.byte OBJ_AUTOSCROLL, $00, $0B
	.byte OBJ_CLOUDSINBGBEGIN, $03, $09
	.byte OBJ_CFIRE_ULCANNON, $13, $0D
	.byte OBJ_AIRSHIPPROP, $16, $13
	.byte OBJ_CFIRE_ULCANNON, $18, $0D
	.byte OBJ_CFIRE_BULLETBILL, $1E, $0C
	.byte OBJ_CFIRE_ULCANNON, $24, $10
	.byte OBJ_CFIRE_LLCANNON, $28, $09
	.byte OBJ_AIRSHIPPROP, $29, $14
	.byte OBJ_CFIRE_BULLETBILL, $2C, $0D
	.byte OBJ_CFIRE_LLCANNON, $2D, $09
	.byte OBJ_CFIRE_4WAY, $38, $0A
	.byte OBJ_AIRSHIPPROP, $3D, $14
	.byte OBJ_CFIRE_URCANNON, $47, $12
	.byte OBJ_CFIRE_BULLETBILL, $4D, $10
	.byte OBJ_CFIRE_URCANNON, $4F, $12
	.byte $FF	; Terminator
