	.byte $00	; Unknown purpose

	.byte OBJ_AUTOSCROLL, $00, $04
	.byte OBJ_CLOUDSINBGBEGIN, $01, $03
	.byte OBJ_CFIRE_BULLETBILL, $15, $0D
	.byte OBJ_CFIRE_BULLETBILL, $18, $0B
	.byte OBJ_CFIRE_ULCANNON2, $21, $0A
	.byte OBJ_CFIRE_BULLETBILL, $29, $0B
	.byte OBJ_CFIRE_BULLETBILL, $2F, $0D
	.byte OBJ_CFIRE_BULLETBILL, $33, $0A
	.byte OBJ_CFIRE_BULLETBILL, $36, $0F
	.byte OBJ_CFIRE_BULLETBILL, $42, $11
	.byte OBJ_CFIRE_BULLETBILL, $42, $13
	.byte OBJ_CFIRE_BULLETBILL, $42, $15
	.byte OBJ_CFIRE_BULLETBILL, $53, $10
	.byte OBJ_CFIRE_BULLETBILL, $53, $12
	.byte OBJ_CFIRE_ROCKYWRENCH, $63, $0F
	.byte OBJ_CFIRE_ROCKYWRENCH, $65, $0F
	.byte OBJ_CFIRE_ROCKYWRENCH, $67, $0F
	.byte OBJ_CFIRE_BULLETBILL, $6E, $0C
	.byte OBJ_CFIRE_BULLETBILL, $71, $0B
	.byte $FF	; Terminator
