	.byte $00	; Unknown purpose

	.byte OBJ_AUTOSCROLL, $00, $01
	.byte OBJ_CLOUDSINBGBEGIN, $01, $03
	.byte OBJ_CFIRE_ROCKYWRENCH, $19, $11
	.byte OBJ_CFIRE_ROCKYWRENCH, $1B, $11
	.byte OBJ_CFIRE_ROCKYWRENCH, $1D, $11
	.byte OBJ_CFIRE_BULLETBILL, $1F, $0E
	.byte OBJ_CFIRE_HLCANNON2, $29, $0F
	.byte OBJ_CFIRE_LLCANNON2, $2D, $10
	.byte OBJ_CFIRE_LLCANNON2, $30, $10
	.byte OBJ_CFIRE_BULLETBILL, $37, $0E
	.byte OBJ_CFIRE_URCANNON2, $3B, $0A
	.byte OBJ_CFIRE_URCANNON2, $3F, $0A
	.byte OBJ_CFIRE_HLCANNON2, $3C, $10
	.byte OBJ_CFIRE_HLCANNON2, $40, $10
	.byte OBJ_BOLTLIFT, $4B, $0C
	.byte OBJ_FIREJET_RIGHT, $4D, $11
	.byte OBJ_FIREJET_LEFT, $54, $10
	.byte OBJ_CFIRE_ROCKYWRENCH, $66, $0C
	.byte OBJ_CFIRE_ROCKYWRENCH, $68, $0C
	.byte OBJ_CFIRE_ROCKYWRENCH, $6A, $0C
	.byte OBJ_FIREJET_LEFT, $6B, $11
	.byte $FF	; Terminator
