	.byte $00	; Unknown purpose

	.byte OBJ_AUTOSCROLL, $00, $05
	.byte OBJ_CLOUDSINBGBEGIN, $01, $03
	.byte OBJ_FIREJET_RIGHT, $14, $0B
	.byte OBJ_AIRSHIPPROP, $15, $0F
	.byte OBJ_AIRSHIPPROP, $14, $11
	.byte OBJ_FIREJET_RIGHT, $1B, $0D
	.byte OBJ_BOLTLIFT, $26, $0A
	.byte OBJ_FIREJET_UPWARD, $29, $0D
	.byte OBJ_FIREJET_UPWARD, $2C, $0D
	.byte OBJ_FIREJET_UPWARD, $2F, $0D
	.byte OBJ_FIREJET_RIGHT, $39, $11
	.byte OBJ_FIREJET_LEFT, $3F, $11
	.byte OBJ_FIREJET_UPSIDEDOWN, $3D, $0E
	.byte OBJ_CFIRE_ROCKYWRENCH, $3A, $0B
	.byte OBJ_FIREJET_UPSIDEDOWN, $4A, $0E
	.byte OBJ_FIREJET_RIGHT, $49, $0A
	.byte OBJ_FIREJET_UPSIDEDOWN, $55, $0C
	.byte OBJ_FIREJET_LEFT, $57, $0E
	.byte OBJ_FIREJET_RIGHT, $52, $11
	.byte OBJ_FIREJET_UPWARD, $58, $11
	.byte OBJ_FIREJET_RIGHT, $6B, $0B
	.byte OBJ_FIREJET_LEFT, $6A, $0D
	.byte OBJ_FIREJET_RIGHT, $68, $10
	.byte OBJ_FIREJET_UPWARD, $62, $11
	.byte OBJ_AIRSHIPPROP, $77, $13
	.byte $FF	; Terminator
