; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $01	; Unknown purpose

	.byte OBJ_PILEDRIVER, $10, $15
	.byte OBJ_PILEDRIVER, $18, $14
	.byte $FF	; Terminator
