; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $01	; Unknown purpose

	.byte OBJ_TREASUREBOX, $0B, $13
	.byte OBJ_TREASUREBOXAPPEAR, $0C, $13
	.byte $FF	; Terminator
