	.byte $01	; Unknown purpose

	.byte OBJ_BUZZYBEATLE, $0A, $17
	.byte OBJ_PATOOIE, $10, $16
	.byte OBJ_GREENPIRANHA, $2C, $12
	.byte OBJ_PARAGOOMBA, $3E, $10
	.byte OBJ_PARAGOOMBAWITHMICROS, $40, $10
	.byte OBJ_PARAGOOMBA, $42, $10
	.byte OBJ_PARAGOOMBAWITHMICROS, $44, $10
	.byte OBJ_PARAGOOMBA, $46, $10
	.byte OBJ_PARAGOOMBAWITHMICROS, $50, $10
	.byte OBJ_PARAGOOMBA, $55, $16
	.byte OBJ_PARAGOOMBAWITHMICROS, $5C, $16
	.byte OBJ_PARAGOOMBA, $5D, $16
	.byte OBJ_PARAGOOMBAWITHMICROS, $5E, $16
	.byte OBJ_PARAGOOMBA, $5F, $16
	.byte OBJ_PARAGOOMBAWITHMICROS, $60, $16
	.byte OBJ_ENDLEVELCARD, $68, $15
	.byte $FF	; Terminator
