; WARNING: Autogenerated file!  Do not put extra data here; editor will not preserve it!
	.byte $01	; Unknown purpose

	.byte OBJ_CANCELEVENT, $04, $19
	.byte OBJ_CHEEPCHEEPBEGIN, $17, $19
	.byte OBJ_CHEEPCHEEPBEGIN, $5C, $19
	.byte OBJ_CANCELEVENT, $70, $19
	.byte $FF	; Terminator
