; Super Mario Bros. 3 Full Disassembly by Southbird 2012
; For more info, see http://www.sonicepoch.com/sm3mix/
;
; PLEASE INCLUDE A CREDIT TO THE SOUTHBIRD DISASSEMBLY
; AND THE ABOVE LINK SOMEWHERE IN YOUR WORKS :)
;
; Original disassembler source generated by DCC6502 version v1.4
; (With labels, comments, and some syntax corrections for nesasm by Southbird)
; For more info about DCC6502, e-mail veilleux@ameth.org
;
; This source file last updated: 2012-03-25 13:37:28.828970596 -0500
; Distribution package date: Fri Apr  6 23:46:16 UTC 2012
;---------------------------------------------------------------------------

	; Ending Sprite list continued from PRG024 ...

	.byte           $01, $28
	.byte $4F, $B7, $01, $20
	.byte $57, $B5, $01, $18
	.byte $6F, $01, $00, $D8
	.byte $6F, $01, $40, $E0
	.byte $7F, $03, $00, $D8
	.byte $7F, $03, $40, $E0
Ending2_EndPicSprites3_End

Ending2_EndPicSprites4:
	.byte $21, $81, $01, $70
	.byte $21, $83, $01, $78
	.byte $21, $85, $01, $80
	.byte $31, $87, $01, $70
	.byte $31, $89, $01, $78
	.byte $31, $41, $01, $80
	.byte $31, $43, $01, $88
	.byte $31, $45, $01, $90
	.byte $3F, $47, $01, $20
	.byte $3F, $49, $01, $28
	.byte $3F, $4B, $01, $30
	.byte $3F, $4D, $01, $38
Ending2_EndPicSprites4_End

Ending2_EndPicSprites5:
	.byte $69, $29, $00, $B0
	.byte $69, $2B, $00, $B8
	.byte $79, $01, $00, $B0
	.byte $79, $03, $00, $B8
	.byte $79, $05, $00, $C0
	.byte $A1, $53, $02, $B8
	.byte $A1, $55, $02, $C0
	.byte $B1, $57, $02, $B8
	.byte $B1, $59, $02, $C0
	.byte $99, $61, $01, $D0
	.byte $99, $63, $01, $D8
	.byte $A9, $65, $01, $D0
	.byte $A9, $67, $01, $D8
Ending2_EndPicSprites5_End

Ending2_EndPicSprites6:
	.byte $69, $19, $40, $20
	.byte $69, $27, $40, $28
	.byte $79, $1F, $40, $20
	.byte $79, $1D, $40, $28
	.byte $79, $1B, $40, $30
	.byte $61, $A7, $41, $58
	.byte $61, $AF, $41, $50
	.byte $A9, $D3, $02, $70
	.byte $A9, $D5, $02, $78
	.byte $A9, $5B, $01, $A0
	.byte $A9, $5D, $01, $A8
Ending2_EndPicSprites6_End

Ending2_EndPicSprites7:
	.byte $41, $F1, $02, $D8
	.byte $41, $F3, $02, $E0
	.byte $51, $E3, $01, $D8
	.byte $51, $E3, $41, $E0
	.byte $51, $67, $42, $C8
	.byte $61, $65, $02, $B8
	.byte $79, $65, $42, $A8
	.byte $89, $37, $40, $A8
	.byte $89, $35, $40, $B0
Ending2_EndPicSprites7_End

Ending2_EndPicSprites8:
	.byte $79, $03, $40, $28
	.byte $79, $01, $40, $30
	.byte $89, $07, $40, $28
	.byte $89, $05, $40, $30
	.byte $99, $51, $02, $50
	.byte $99, $5F, $02, $58
	.byte $90, $69, $01, $B0
	.byte $90, $6B, $01, $B8
	.byte $90, $6D, $01, $C0
	.byte $90, $6F, $01, $C8
	.byte $A0, $71, $01, $B0
	.byte $A0, $73, $01, $B8
	.byte $A0, $75, $01, $C0
	.byte $A0, $77, $01, $C8
	.byte $B0, $79, $01, $B0
	.byte $B0, $7B, $01, $B8
	.byte $B0, $7D, $01, $C0
	.byte $B0, $7F, $01, $C8
Ending2_EndPicSprites8_End


	; Split address, parallel tables for the starting address of the end picture for each world
EndPicByWorld_H:.byte HIGH(EndPic_World1), HIGH(EndPic_World2), HIGH(EndPic_World3), HIGH(EndPic_World4)
		.byte HIGH(EndPic_World5), HIGH(EndPic_World6), HIGH(EndPic_World7), HIGH(EndPic_World8)

EndPicByWorld_L:.byte LOW(EndPic_World1), LOW(EndPic_World2), LOW(EndPic_World3), LOW(EndPic_World4)
		.byte LOW(EndPic_World5), LOW(EndPic_World6), LOW(EndPic_World7), LOW(EndPic_World8)

	; $C0 bytes are expected to be loaded into the Ending_CmdBuffer buffer.
	; The EndPics are mostly raw with a simple compression, specifically if
	; bit 7 is set, that byte is duplicated once in the buffer, sans bit 7.
	; So for example:
	; The value $70 inserts $70 once
	; The value $F1 inserts $71 twice

EndPic_World1:
	.byte $70, $F1, $F1, $F1, $F1, $F1, $F1, $F1, $72, $73, $BF, $3F, $00, $04, $06, $04
	.byte $00, $04, $00, $04, $06, $BF, $73, $73, $BF, $3F, $05, $BF, $3F, $05, $BF, $3F
	.byte $05, $BF, $73, $73, $04, $0E, $04, $07, $BF, $3F, $63, $04, $00, $04, $0A, $BF
	.byte $73, $73, $BF, $3F, $0B, $BF, $3F, $05, $BF, $BF, $BF, $73, $73, $BF, $3F, $63
	.byte $04, $62, $04, $10, $BF, $38, $44, $39, $3F, $73, $73, $3F, $D5, $05, $55, $BF
	.byte $3F, $38, $44, $49, $3D, $3C, $3F, $73, $73, $D5, $65, $63, $65, $0A, $04, $06
	.byte $1E, $06, $04, $3E, $3C, $3F, $73, $73, $55, $E5, $05, $E5, $55, $05, $3C, $D5
	.byte $55, $3C, $3F, $73, $73, $55, $E5, $00, $04, $06, $04, $00, $48, $C4, $44, $49
	.byte $3F, $73, $73, $D5, $D5, $D5, $D5, $D5, $D5, $D5, $73, $74, $F1, $F1, $F1, $F1
	.byte $F1, $F1, $F1, $75

EndPic_World2:
	.byte $70, $F1, $F1, $F1, $F1, $F1, $F1, $F1, $72, $73, $35, $03, $04, $06, $5C, $0A
	.byte $04, $06, $04, $00, $04, $06, $65, $2F, $73, $73, $66, $05, $66, $05, $2F, $55
	.byte $02, $05, $E5, $65, $05, $E5, $73, $73, $66, $63, $5C, $00, $04, $06, $04, $66
	.byte $E6, $65, $63, $2F, $65, $73, $73, $0C, $05, $66, $05, $66, $66, $66, $05, $66
	.byte $3D, $66, $05, $2F, $65, $73, $73, $04, $07, $04, $07, $04, $1F, $5C, $63, $66
	.byte $3E, $66, $63, $66, $65, $73, $73, $66, $AF, $05, $66, $E6, $05, $0C, $05, $0C
	.byte $05, $66, $66, $73, $73, $66, $65, $2F, $63, $65, $06, $5C, $00, $66, $63, $04
	.byte $0C, $E6, $73, $73, $E5, $AF, $2F, $05, $66, $05, $2F, $E6, $05, $E6, $73, $73
	.byte $66, $E5, $66, $2F, $10, $04, $07, $04, $06, $04, $07, $E6, $73, $73, $E6, $E6
	.byte $E6, $E6, $E6, $E6, $E6, $73, $74, $F1, $F1, $F1, $F1, $F1, $F1, $F1, $75

EndPic_World3:
	.byte $70, $F1, $F1, $F1, $F1, $F1, $F1, $F1, $72, $73, $04, $0A, $AF, $23, $E7, $E7
	.byte $6B, $B4, $17, $67, $73, $73, $2F, $5C, $13, $14, $27, $E7, $E7, $25, $BF, $23
	.byte $67, $73, $73, $94, $27, $E7, $E7, $E7, $25, $5C, $3F, $23, $67, $73, $73, $E7
	.byte $E7, $E7, $E7, $67, $31, $44, $3B, $27, $67, $73, $73, $E7, $E7, $6B, $B4, $B4
	.byte $35, $3F, $23, $E7, $73, $73, $E7, $6B, $34, $37, $5C, $BF, $3D, $3F, $3F, $23
	.byte $E7, $73, $73, $E7, $25, $3F, $21, $44, $2D, $39, $3E, $04, $06, $4E, $1F, $67
	.byte $73, $73, $E7, $25, $3F, $3C, $3F, $5C, $46, $94, $14, $27, $E7, $73, $73, $E7
	.byte $26, $14, $30, $94, $27, $E7, $E7, $E7, $73, $73, $E7, $E7, $E7, $E7, $E7, $E7
	.byte $E7, $73, $74, $F1, $F1, $F1, $F1, $F1, $F1, $F1, $75

EndPic_World4:
	.byte $70, $F1, $F1, $F1, $F1, $F1, $F1, $F1, $72, $73, $E7, $E7, $E7, $E7, $E7, $6B
	.byte $B4, $34, $73, $73, $34, $34, $20, $34, $17, $E7, $67, $6B, $34, $35, $52, $55
	.byte $52, $73, $73, $04, $0E, $1E, $1F, $23, $67, $6B, $34, $35, $0A, $04, $00, $04
	.byte $06, $73, $73, $14, $1A, $30, $3A, $32, $6B, $35, $3D, $D2, $38, $22, $12, $44
	.byte $73, $73, $67, $4C, $67, $26, $27, $25, $55, $3E, $04, $06, $3C, $07, $1E, $62
	.byte $73, $73, $6B, $1B, $17, $67, $6B, $41, $6A, $55, $D2, $48, $22, $11, $44, $73
	.byte $73, $25, $1F, $23, $67, $26, $27, $31, $44, $45, $10, $04, $00, $04, $06, $73
	.byte $73, $35, $2F, $33, $17, $E7, $25, $52, $55, $52, $13, $94, $14, $73, $73, $55
	.byte $AF, $33, $B4, $4A, $C4, $44, $4B, $B4, $34, $73, $73, $D5, $D5, $D5, $D5, $D5
	.byte $D5, $D5, $73, $74, $F1, $F1, $F1, $F1, $F1, $F1, $F1, $75

EndPic_World5:
	.byte $70, $F1, $F1, $F1, $F1, $F1, $F1, $F1, $72, $73, $BF, $BF, $47, $43, $A4, $A4
	.byte $53, $D5, $0A, $73, $73, $BF, $BF, $42, $A4, $A4, $24, $53, $D5, $05, $73, $73
	.byte $B6, $B6, $43, $24, $50, $1F, $D1, $59, $03, $04, $00, $73, $73, $A4, $A4, $50
	.byte $51, $59, $05, $D5, $55, $05, $55, $05, $73, $73, $A4, $50, $51, $59, $03, $0B
	.byte $07, $04, $00, $04, $07, $55, $10, $73, $73, $D1, $59, $D5, $05, $D5, $D5, $D5
	.byte $55, $05, $73, $73, $D5, $55, $10, $04, $07, $04, $62, $04, $06, $04, $00, $04
	.byte $07, $73, $73, $55, $3D, $D5, $D5, $55, $05, $55, $05, $D5, $55, $05, $73, $73
	.byte $55, $3E, $04, $06, $04, $00, $04, $00, $55, $63, $04, $0A, $04, $00, $73, $73
	.byte $DC, $DC, $DC, $DC, $DC, $DC, $DC, $73, $74, $F1, $F1, $F1, $F1, $F1, $F1, $F1
	.byte $75

EndPic_World6:
	.byte $70, $F1, $F1, $F1, $F1, $F1, $F1, $F1, $72, $73, $60, $55, $33, $B4, $17, $67
	.byte $6B, $34, $17, $E7, $E7, $73, $73, $6A, $D5, $D5, $33, $17, $25, $60, $23, $E7
	.byte $E7, $73, $73, $00, $04, $06, $04, $06, $55, $23, $26, $14, $27, $6B, $B4, $17
	.byte $73, $73, $05, $38, $44, $39, $05, $55, $33, $20, $34, $20, $35, $3F, $3D, $23
	.byte $73, $73, $07, $3C, $62, $1E, $07, $0B, $06, $1E, $06, $1E, $06, $04, $3E, $23
	.byte $73, $73, $05, $48, $44, $49, $05, $02, $13, $30, $14, $30, $6A, $3F, $5C, $23
	.byte $73, $73, $63, $04, $06, $04, $00, $60, $33, $17, $E7, $26, $94, $27, $73, $73
	.byte $E0, $E0, $E0, $60, $33, $17, $E7, $E7, $67, $73, $73, $3F, $E0, $E0, $E0, $60
	.byte $33, $B4, $B4, $34, $73, $73, $DC, $DC, $DC, $DC, $DC, $DC, $DC, $73, $74, $F1
	.byte $F1, $F1, $F1, $F1, $F1, $F1, $75

EndPic_World7:
	.byte $70, $F1, $F1, $F1, $F1, $F1, $F1, $F1, $72, $73, $34, $20, $34, $17, $6B, $B4
	.byte $B4, $B4, $20, $34, $17, $73, $73, $10, $4F, $00, $23, $25, $00, $04, $06, $04
	.byte $1F, $1D, $3C, $1D, $23, $73, $73, $1D, $3C, $05, $23, $25, $05, $9D, $1D, $05
	.byte $1D, $3C, $1F, $23, $73, $73, $1F, $3C, $1F, $23, $25, $10, $04, $06, $04, $00
	.byte $04, $0A, $1D, $23, $73, $73, $12, $11, $3B, $27, $26, $3A, $44, $22, $C4, $12
	.byte $44, $3B, $27, $73, $73, $4F, $1F, $23, $E7, $1F, $0B, $00, $04, $06, $4F, $62
	.byte $23, $67, $73, $73, $3C, $05, $23, $E7, $25, $52, $3D, $52, $5C, $3C, $05, $23
	.byte $67, $73, $73, $3C, $0A, $23, $E7, $25, $5C, $3E, $04, $06, $1E, $07, $23, $67
	.byte $73, $73, $11, $44, $4B, $B4, $4A, $C4, $C4, $11, $44, $4B, $34, $73, $73, $DC
	.byte $DC, $DC, $DC, $DC, $DC, $DC, $73, $74, $F1, $F1, $F1, $F1, $F1, $F1, $F1, $75

EndPic_World8:
	.byte $70, $F1, $F1, $F1, $F1, $F1, $F1, $F1, $72, $73, $AA, $AA, $AA, $AA, $AA, $AA
	.byte $AA, $73, $73, $AA, $AA, $AA, $AA, $AA, $AA, $AA, $73, $73, $0F, $AA, $2A, $0F
	.byte $AA, $AA, $0F, $AA, $2A, $0F, $73, $73, $2E, $D4, $54, $68, $D4, $D4, $68, $D4
	.byte $54, $2E, $73, $73, $2E, $5B, $2B, $5B, $2B, $5B, $2B, $5B, $2B, $DB, $6C, $6D
	.byte $2E, $73, $73, $2E, $1F, $61, $69, $0B, $69, $61, $69, $61, $69, $61, $6E, $6F
	.byte $2E, $73, $73, $0F, $D4, $54, $0F, $D4, $D4, $0F, $D4, $54, $0F, $73, $73, $9C
	.byte $9C, $9C, $9C, $9C, $9C, $9C, $73, $73, $AA, $AA, $AA, $AA, $AA, $AA, $AA, $73
	.byte $73, $AA, $AA, $AA, $AA, $AA, $AA, $AA, $73, $74, $F1, $F1, $F1, $F1, $F1, $F1
	.byte $F1, $75

	; Split address, parallel tables for the starting VRAM address of the end picture for each world
EndPic_VRAMStart_H:	.byte $28, $28, $28, $29, $29, $28, $28, $28	; High
EndPic_VRAMStart_L:	.byte $E3, $AD, $E9, $67, $23, $AD, $A3, $A9	; Low

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; This table contains commands for Video_Misc_Updates2 which tells
; it how to generate certain graphical elements programatically
;
; Note: See Video_Upd_Table in PRG030 for format
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Remember that the left edge is typically clipped, so nothing is visible there...
Video_Upd_Table2:
	.word Graphics_Buffer		; $00 - Graphics buffer for dynamically generated content
	.word Title_Load_Palette	; $01 - Loads palette for title screen (and falls into Title_Checkerboard_Floor)
	.word PRG025_CA9B		; $02 - ???
	.word Title_FadeIn_1		; $03 - Title screen colors fade in part 1
	.word Title_FadeIn_2		; $04 - Title screen colors fade in part 2
	.word Title_FadeIn_3		; $05 - Title screen colors fade in part 3
	.word Title_FadeIn_4		; $06 - Title screen colors fade in part 4
	.word Title_LoadMenu		; $07 - Loads the 1P/2P select menu

	; The title screen -- this is too complicated/large to load in one single buffer
	; instance, so it is broken up across several frames in chunks.  Maybe I could
	; explain what's being loaded a little better, but whatever :}
	.word TitleScreen_LogoLine01	; $08 - Title Screen part 01 Title Sequence begin
	.word TitleScreen_LogoLine02	; $09 - Title Screen part 02
	.word TitleScreen_LogoLine03	; $0A - Title Screen part 03
	.word TitleScreen_LogoLine04	; $0B - Title Screen part 04
	.word TitleScreen_LogoLine05	; $0C - Title Screen part 05
	.word TitleScreen_LogoLine06	; $0D - Title Screen part 06
	.word TitleScreen_LogoLine07	; $0E - Title Screen part 07
	.word TitleScreen_LogoLine08	; $0F - Title Screen part 08
	.word TitleScreen_LogoLine09	; $10 - Title Screen part 09
	.word TitleScreen_LogoLine10	; $11 - Title Screen part 10
	.word TitleScreen_LogoLine11	; $12 - Title Screen part 11
	.word TitleScreen_LogoLine12	; $13 - Title Screen part 12
	.word TitleScreen_LogoLine13	; $14 - Title Screen part 13
	.word TitleScreen_LogoLine14	; $15 - Title Screen part 14
	.word TitleScreen_LogoLine15	; $16 - Title Screen part 15
	.word TitleScreen_LogoLine16	; $17 - Title Screen part 16
	.word TitleScreen_LogoLine17	; $18 - Title Screen part 17
	.word TitleScreen_LogoLine18	; $19 - Title Screen part 18
	.word TitleScreen_LogoLine19	; $1A - Title Screen part 19
	.word TitleScreen_LogoLine20	; $1B - Title Screen part 20
	.word TitleScreen_LogoLine21	; $1C - Title Screen part 21
	.word TitleScreen_LogoLine22	; $1D - Title Screen part 22
	.word TitleScreen_LogoLine23	; $1E - Title Screen part 23
	.word TitleScreen_LogoLine24	; $1F - Title Screen part 24
	.word TitleScreen_LogoAttr1	; $20 - Title Screen part 25
	.word TitleScreen_LogoAttr2	; $21 - Title Screen part 26
	.word TitleScreen_DarkPal	; $22 - Title Screen part 27 Sequence end

	.word Title_Checkerboard_Floor	; $23 - The black & white squares at the beginning 
	.word Ending_CurtainExtension	; $24 - Slightly longer curtain in ending
	.word PRG025_CCCE		; $25 - ???
	.word EndSeq_WorldFadeIn1	; $26 - End pic world fade in effect part 1
	.word EndSeq_WorldFadeIn2	; $27 - End pic world fade in effect part 2
	.word EndSeq_WorldFadeIn3	; $28 - End pic world fade in effect part 3
	.word EndSeq_WorldFadeIn4	; $29 - End pic world fade in effect part 4
	.word PRG025_CD82		; $2A - ???
	.word PRG025_CDA6		; $2B - ???
	.word PRG025_CDBB		; $2C - ???
	.word PRG025_CDD1		; $2D - ???
	.word PRG025_CDE7		; $2E - ???
	.word PRG025_CE02		; $2F - ???
	.word PRG025_CE19		; $30 - ???
	.word PRG025_CE2D		; $31 - 
	.word PRG025_CE43		; $32 - 
	.word PRG025_CE57		; $33 - 
	.word PRG025_CE6D		; $34 - 
	.word PRG025_CE7B		; $35 - 
	.word PRG025_CE91		; $36 - 
	.word PRG025_CE9E		; $37 - 
	.word PRG025_CEAE		; $38 - 
	.word PRG025_CEB6		; $39 - 
	.word PRG025_CEC5		; $3A - 
	.word PRG025_CEE2		; $3B - 
	.word PRG025_CEFF		; $3C - 
	.word PRG025_CF0A		; $3D - 
	.word PRG025_CF20		; $3E - 
	.word PRG025_CF43		; $3F - 
	.word PRG025_CF6B		; $40 - 
	.word PRG025_CF8A		; $41 - 
	.word PRG025_CF9E		; $42 - 
	.word PRG025_CFB2		; $43 - 
	.word PRG025_CFC8		; $44 - 
	.word PRG025_CFED		; $45 - 
	.word PRG025_CFF6		; $46 - 
	.word PRG025_D009		; $47 - 
	.word PRG025_D01F		; $48 - 
	.word PRG025_D035		; $49 - 
	.word PRG025_D044		; $4A - 
	.word PRG025_D051		; $4B - 
	.word PRG025_D059		; $4C - 
	.word EndSeq_World1Pal		; $4D - Ending pic World 1 full palette
	.word EndSeq_World2Pal		; $4E - Ending pic World 2 full palette
	.word EndSeq_World3Pal		; $4F - Ending pic World 3 full palette
	.word EndSeq_World4Pal		; $50 - Ending pic World 4 full palette
	.word EndSeq_World5Pal		; $51 - Ending pic World 5 full palette
	.word EndSeq_World6Pal		; $52 - Ending pic World 6 full palette
	.word EndSeq_World7Pal		; $53 - Ending pic World 7 full palette
	.word EndSeq_World8Pal		; $54 - Ending pic World 8 full palette
	.word EndSeq_PrincessChamber	; $55 - Princess's chamber itself
	.word EndSeq_Fade4		; $56 - Princess's chamber "fade in/out" effect part 4
	.word EndSeq_Fade3		; $57 - Princess's chamber "fade in/out" effect part 3
	.word EndSeq_Fade2		; $58 - Princess's chamber "fade in/out" effect part 2
	.word EndSeq_Fade1		; $59 - Princess's chamber "fade in/out" effect part 1
	.word EndSeq_Fade0		; $5A - Princess's chamber "fade out" lead (then goes back through the above)
	.word PRG025_D4B5		; $5B - ?? Sprite palette
	.word EndSeq_CurtainFadeIn1	; $5C - Curtain fade in effect part 1
	.word EndSeq_CurtainFadeIn2	; $5D - Curtain fade in effect part 2
	.word EndSeq_CurtainFadeIn3	; $5E - Curtain fade in effect part 3
	.word PRG025_D505		; $5F - 

Title_Load_Palette:
	; This is the initial palette applied to the title screen

	vaddr $3F00
	.byte 32	; 32 bytes to follow (32 colors)

	; The colors!
	.byte $0F, $0F, $30, $16, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F
	.byte $0F, $16, $36, $0F, $0F, $2A, $36, $0F, $0F, $27, $30, $0F, $0F, $2A, $30, $0F

	; Falls into...

Title_Checkerboard_Floor:
	vaddr $22E0	; Bottom of nametable
	.byte 32	; 32 bytes to follow
	.byte $18, $19, $18, $19, $18, $19, $18, $19, $18, $19, $18, $19, $18, $19, $18, $19
	.byte $18, $19, $18, $19, $18, $19, $18, $19, $18, $19, $18, $19, $18, $19, $18, $19

	vaddr $2B00
	.byte 32	; 32 bytes to follow
	.byte $15, $15, $16, $16, $15, $15, $16, $16, $15, $15, $16, $16, $15, $15, $16, $16
	.byte $15, $15, $16, $16, $15, $15, $16, $16, $15, $15, $16, $16, $15, $15, $16, $16
	
	vaddr $2B20
	.byte 32	; 32 bytes to follow
	.byte $E6, $E6, $E7, $E7, $E6, $E6, $E7, $E7, $E6, $E6, $E7, $E7, $E6, $E6, $E7, $E7
	.byte $E6, $E6, $E7, $E7, $E6, $E6, $E7, $E7, $E6, $E6, $E7, $E7, $E6, $E6, $E7, $E7

	vaddr $2B40
	.byte 32	; 32 bytes to follow
	.byte $F6, $F6, $F7, $F7, $F6, $F6, $F7, $F7, $F6, $F6, $F7, $F7, $F6, $F6, $F7, $F7
	.byte $F6, $F6, $F7, $F7, $F6, $F6, $F7, $F7, $F6, $F6, $F7, $F7, $F6, $F6, $F7, $F7

	vaddr $2B60
	.byte 32	; 32 bytes to follow
	.byte $5D, $5D, $5F, $5F, $5D, $5D, $5F, $5F, $5D, $5D, $5F, $5F, $5D, $5D, $5F, $5F
	.byte $5D, $5D, $5F, $5F, $5D, $5D, $5F, $5F, $5D, $5D, $5F, $5F, $5D, $5D, $5F, $5F

	; Terminator!
	.byte $00

TitleScreen_LogoLine01:
	vaddr $2000
	.byte $20, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08
	.byte $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08
	.byte $09

	; Terminator
	.byte $00

TitleScreen_LogoLine02:
	vaddr $2020
	.byte $20, $18, $19, $18, $19, $18, $19, $18, $19, $18, $19, $18, $19, $18, $19, $18
	.byte $19, $18, $19, $18, $19, $18, $19, $18, $19, $18, $19, $18, $19, $18, $19, $18
	.byte $19

	; Terminator
	.byte $00

TitleScreen_LogoLine03:
	vaddr $2040
	.byte $20, $28, $29, $28, $29, $28, $29, $28, $29, $28, $29, $28, $29, $28, $29, $28
	.byte $29, $28, $29, $28, $29, $28, $29, $28, $29, $28, $29, $28, $29, $28, $29, $28
	.byte $29

	; Terminator
	.byte $00

TitleScreen_LogoLine04:
	vaddr $2060
	.byte VU_REPEAT | $20, $5C

	; Terminator
	.byte $00

TitleScreen_LogoLine05:
	vaddr $2080
	.byte VU_REPEAT | $0B, $5C

	vaddr $208B
	.byte $15, $30, $31, $32, $33, $34, $35, $36, $37, $38, $39, $3A, $5C, $5C, $5C, $5C
	.byte $3B, $3C, $3D, $3E, $5C, $5C

	; Terminator
	.byte $00

TitleScreen_LogoLine06:
	vaddr $20A0
	.byte VU_REPEAT | $0B, $5C

	vaddr $20AB
	.byte $15, $40, $41, $42, $43, $44, $45, $46, $47, $48, $49, $4A, $5C, $5C, $5C, $5C
	.byte $4B, $4C, $4D, $4E, $5C, $5C

	; Terminator
	.byte $00

TitleScreen_LogoLine07:
	vaddr $20C0
	.byte $16, $5C, $5C, $3B, $3C, $3D, $3E, $5C, $5C, $5C, $5C, $5C, $50, $51, $52, $53
	.byte $54, $55, $56, $57, $58, $59, $5A

	vaddr $20D6
	.byte VU_REPEAT | $0A, $5C

	; Terminator
	.byte $00

TitleScreen_LogoLine08:
	vaddr $20E0
	.byte $16, $5C, $5C, $4B, $4C, $4D, $4E, $5C, $5C, $5C, $5C, $5C, $60, $61, $62, $63
	.byte $64, $65, $66, $67, $68, $69, $6A

	vaddr $20F6
	.byte VU_REPEAT | $0A, $5C

	; Terminator
	.byte $00

TitleScreen_LogoLine09:
	vaddr $2100
	.byte $20, $5C, $5C, $5C, $5C, $5C, $70, $71, $72, $73, $74, $75, $76, $77, $78, $79
	.byte $7A, $7B, $5C, $7D, $7E, $7F, $C0, $C1, $C2, $C3, $C4, $C5, $5C, $5C, $5C, $5C
	.byte $5C

	; Terminator
	.byte $00

TitleScreen_LogoLine10:
	vaddr $2120
	.byte $20, $5C, $5C, $5C, $5C, $5C, $80, $81, $82, $83, $84, $85, $86, $87, $88, $89
	.byte $8A, $8B, $8C, $8D, $8E, $8F, $D0, $D1, $D2, $D3, $D4, $D5, $5C, $5C, $5C, $5C
	.byte $5C

	; Terminator
	.byte $00

TitleScreen_LogoLine11:
	vaddr $2140
	.byte $20, $5C, $5C, $5C, $5C, $5C, $90, $91, $92, $93, $94, $95, $96, $97, $98, $99
	.byte $9A, $9B, $9C, $9D, $9E, $9F, $E0, $E1, $E2, $E3, $E4, $E5, $5C, $5C, $5C, $5C
	.byte $5C

	; Terminator
	.byte $00

TitleScreen_LogoLine12:
	vaddr $2160
	.byte $20, $5C, $5C, $5C, $5C, $5C, $A0, $A1, $A2, $A3, $A4, $A5, $A6, $A7, $A8, $A9
	.byte $AA, $AB, $AC, $AD, $AE, $AF, $F0, $F1, $F2, $F3, $F4, $F5, $5C, $5C, $5C, $5C
	.byte $5C

	; Terminator
	.byte $00

TitleScreen_LogoLine13:
	vaddr $2180
	.byte $20, $5B, $6B, $5C, $5C, $5C, $B0, $B1, $B2, $B3, $B4, $B5, $B6, $B7, $B8, $B9
	.byte $BA, $BB, $BC, $BD, $BE, $BF, $C6, $C7, $C8, $D6, $D7, $D8, $E8, $04, $05, $06
	.byte $07

	; Terminator
	.byte $00

TitleScreen_LogoLine14:
	vaddr $21A0
	.byte VU_REPEAT | $0E, $5C

	vaddr $21AE
	.byte $12, $C9, $CA, $CB, $CC, $CD, $CE, $CF, $5C, $5C, $5C, $5C, $5C, $5C, $5C, $14
	.byte $21, $21, $17

	; Terminator
	.byte $00

TitleScreen_LogoLine15:
	vaddr $21C0
	.byte VU_REPEAT | $0E, $5C

	vaddr $21CE
	.byte $12, $D9, $DA, $DB, $DC, $DD, $5C, $5C, $5C, $5C, $5C, $5C, $5C, $5C, $5C, $20
	.byte $21, $21, $23

	; Terminator
	.byte $00

TitleScreen_LogoLine16:
	vaddr $21E0
	.byte VU_REPEAT | $0E, $5C

	vaddr $21EE
	.byte $12, $E9, $EA, $EB, $EC, $ED, $5C, $5C, $5C, $5C, $5C, $5C, $5C, $5C, $5C, $20
	.byte $21, $21, $23

	; Terminator
	.byte $00

TitleScreen_LogoLine17:
	vaddr $2200
	.byte $20, $04, $05, $06, $07, $5C, $5C, $5C, $5C, $5C, $5C, $5C, $5C, $5C, $5C, $F9
	.byte $FA, $FB, $FF, $FD, $FE, $5C, $5C, $5C, $5C, $5C, $5C, $04, $05, $02, $03, $21
	.byte $23

	; Terminator
	.byte $00

TitleScreen_LogoLine18:
	vaddr $2220
	.byte $20, $14, $21, $21, $22, $24, $25, $5C, $5C, $5C, $5C, $5C, $5C, $5C, $5C, $6C
	.byte $6D, $6E, $6F, $DE, $DF, $5C, $5C, $5C, $5C, $5C, $5C, $14, $21, $21, $13, $21
	.byte $23

	; Terminator
	.byte $00

TitleScreen_LogoLine19:
	vaddr $2240
	.byte $20, $20, $21, $21, $23, $5F, $11, $5C, $5C, $5C, $5C, $5C, $5C, $5C, $5C, $5C
	.byte $5C, $EE, $EF, $5C, $5C, $5C, $5C, $5C, $5C, $5C, $5C, $20, $21, $21, $21, $21
	.byte $23

	; Terminator
	.byte $00

TitleScreen_LogoLine20:
	vaddr $2260
	.byte $06, $20, $21, $21, $23, $5F, $5F

	vaddr $2266
	.byte VU_REPEAT | $14, $5C

	vaddr $227A
	.byte $06, $20, $21, $21, $21, $21, $23

	; Terminator
	.byte $00

TitleScreen_LogoLine21:
	vaddr $2280
	.byte $06, $20, $21, $00, $01, $26, $27

	vaddr $2286
	.byte VU_REPEAT | $14, $5C

	vaddr $229A
	.byte $06, $20, $21, $21, $21, $21, $23

	; Terminator
	.byte $00

TitleScreen_LogoLine22:
	vaddr $22A0
	.byte $08, $20, $21, $10, $21, $21, $22, $24, $25

	vaddr $22A8
	.byte VU_REPEAT | $12, $5C

	vaddr $22BA
	.byte $06, $20, $21, $21, $21, $21, $23

	; Terminator
	.byte $00

TitleScreen_LogoLine23:
	vaddr $22C0
	.byte $08, $20, $21, $21, $21, $21, $23, $5F, $11

	vaddr $22C8
	.byte VU_REPEAT | $10, $5C

	vaddr $22D8
	.byte $08, $04, $05, $02, $03, $21, $21, $21, $23

	; Terminator
	.byte $00

TitleScreen_LogoLine24:
	vaddr $22E0
	.byte $08, $20, $21, $21, $21, $21, $23, $5F, $5F

	vaddr $22E8
	.byte VU_REPEAT | $10, $5C

	vaddr $22F8
	.byte $08, $14, $21, $21, $13, $21, $21, $21, $23

	; Terminator
	.byte $00

TitleScreen_LogoAttr1:
	vaddr $23C0
	.byte $20, $F0, $F0, $F0, $F0, $F0, $F0, $F0, $F0, $2A, $8A, $66, $55, $55, $99, $A2
	.byte $A8, $AA, $55, $55, $55, $55, $55, $55, $A9, $A8, $A6, $A5, $ED, $77, $B5, $A5
	.byte $AA

	; Terminator
	.byte $00

TitleScreen_LogoAttr2:
	vaddr $23E0
	.byte $20, $AA, $AA, $0A, $0E, $0F, $0B, $AA, $AA, $AA, $AA, $22, $00, $00, $00, $AA
	.byte $AA, $00, $00, $00, $00, $00, $00, $00, $00, $0A, $0A, $0A, $0A, $0A, $0A, $0A
	.byte $0A

	; Terminator
	.byte $00

TitleScreen_DarkPal:
	vaddr $3F00
	.byte $10, $0F, $0F, $30, $0F, $0F, $0F, $21, $02, $0F, $0F, $0F, $0F, $0F, $0F, $27
	.byte $02

	; Terminator
	.byte $00

PRG025_CA9B:
	vaddr $3F00
	.byte 16	; 16 bytes (colors) to follow...
	.byte $0F, $0F, $30, $16, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F

	; Terminator
	.byte $00

Title_FadeIn_1:
	vaddr $3F00
	.byte 16	; 16 bytes (colors) to follow...
	.byte $07, $0F, $00, $06, $07, $0F, $01, $02, $07, $0F, $0A, $0A, $07, $0F, $07, $02
	.byte $00	; Terminator

Title_FadeIn_2:
	vaddr $3F00
	.byte 16	; 16 bytes (colors) to follow...
	.byte $17, $0F, $10, $16, $17, $0F, $11, $02, $17, $0F, $1A, $1A, $17, $0F, $17, $02
	.byte $00	; Terminator

Title_FadeIn_3:
	vaddr $3F00
	.byte 16	; 16 bytes (colors) to follow...
	.byte $27, $0F, $20, $16, $27, $0F, $21, $02, $27, $0F, $2A, $1A, $27, $0F, $27, $02
	.byte $00	; Terminator

Title_FadeIn_4:
	vaddr $3F00
	.byte 16	; 16 bytes (colors) to follow...
	.byte $37, $0F, $30, $16, $37, $0F, $21, $02, $37, $0F, $2A, $1A, $37, $0F, $27, $02
	.byte $00	; Terminator

Title_LoadMenu:

	; 1 PLAYER GAME
	vaddr $226A
	.byte 13	; 13 bytes to follow
	.byte $0E, $5C, $0A, $0B, $0C, $1A, $1B, $0D, $5C, $1C, $0C, $1D, $1B

	; 2 PLAYER GAME
	vaddr $22AA
	.byte 13	; 13 bytes to follow
	.byte $1E, $5C, $0A, $0B, $0C, $1A, $1B, $0D, $5C, $1C, $0C, $1D, $1B

	; C 1988 Nintendo
	vaddr $22EA
	.byte 13	; 13 bytes to follow
	.byte $3F, $5C, $0E, $0F, $1F, $1F, $5C, $2A, $2B, $2C, $2D, $2E, $2F

	.byte $00	; Terminator

Ending_CurtainExtension:
	vaddr $22E0
	.byte $20, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08
	.byte $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08
	.byte $09

	vaddr $2300
	.byte $20, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08
	.byte $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08
	.byte $09

	vaddr $2320
	.byte $20, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08
	.byte $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08
	.byte $09

	vaddr $2340
	.byte $20, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08
	.byte $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08
	.byte $09

	vaddr $2360
	.byte $20, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08
	.byte $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08
	.byte $09

	vaddr $2380
	.byte $20, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08
	.byte $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08
	.byte $09

	vaddr $23A0
	.byte $20, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08
	.byte $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08
	.byte $09

	vaddr $2800
	.byte $20, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08
	.byte $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08
	.byte $09

	vaddr $2820
	.byte $20, $18, $19, $18, $19, $18, $19, $18, $19, $18, $19, $18, $19, $18, $19, $18
	.byte $19, $18, $19, $18, $19, $18, $19, $18, $19, $18, $19, $18, $19, $18, $19, $18
	.byte $19

	vaddr $2840
	.byte $20, $28, $29, $28, $29, $28, $29, $28, $29, $28, $29, $28, $29, $28, $29, $28
	.byte $29, $28, $29, $28, $29, $28, $29, $28, $29, $28, $29, $28, $29, $28, $29, $28
	.byte $29

	vaddr $23C0
	.byte VU_REPEAT | $20, $00

	vaddr $23E0
	.byte VU_REPEAT | $10, $00

	vaddr $23F0
	.byte VU_REPEAT | $10, $00

	vaddr $2BC0
	.byte VU_REPEAT | $08, $A0

	vaddr $2BC8
	.byte VU_REPEAT | $08, $AA

	vaddr $2BD0
	.byte VU_REPEAT | $10, $AA

	vaddr $2BE0
	.byte VU_REPEAT | $10, $AA

	vaddr $3F00
	.byte $20, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F
	.byte $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F
	.byte $0F

	; Terminator
	.byte $00

PRG025_CCCE:
	vaddr $3F00
	.byte $20, $0F, $0F, $30, $16, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F
	.byte $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F
	.byte $0F

	; Terminator
	.byte $00

EndSeq_WorldFadeIn1:
	vaddr $3F00
	.byte $20, $0F, $0F, $30, $16, $0F, $0F, $0F, $00, $0F, $0F, $00, $0F, $0F, $0F, $00
	.byte $00, $0F, $0F, $0F, $00, $0F, $00, $0F, $0F, $0F, $00, $0F, $0F, $0F, $00, $0F
	.byte $0F

	; Terminator
	.byte $00

EndSeq_WorldFadeIn2:
	vaddr $3F00
	.byte $20, $0F, $0F, $30, $16, $0F, $0F, $00, $10, $0F, $00, $10, $00, $0F, $00, $10
	.byte $10, $0F, $00, $00, $10, $0F, $10, $00, $00, $0F, $10, $00, $00, $0F, $10, $00
	.byte $00

	; Terminator
	.byte $00

EndSeq_WorldFadeIn3:
	vaddr $3F00
	.byte $20, $0F, $0F, $30, $16, $0F, $00, $10, $30, $0F, $10, $30, $10, $0F, $10, $30
	.byte $30, $0F, $10, $10, $30, $0F, $30, $10, $10, $0F, $30, $10, $10, $0F, $30, $10
	.byte $10

	; Terminator
	.byte $00

EndSeq_WorldFadeIn4:
	vaddr $3F00
	.byte $20, $0F, $0F, $30, $16, $0F, $27, $2A, $36, $0F, $3C, $30, $37, $0F, $21, $2A
	.byte $36, $0F, $10, $36, $0F, $0F, $25, $36, $0F, $0F, $29, $36, $0F, $0F, $29, $36
	.byte $0F

	; Terminator
	.byte $00

PRG025_CD82:
	.byte $28, $F4, $07, $DE, $F4, $EF, $F1, $E3 ; $CD7A - $CD89
	.byte $5C, $77, $29, $74, $0A, $E8, $EF, $E0, $F8, $F8, $5C, $F1, $E0, $F3, $E3, $2A ; $CD8A - $CD99
	.byte $5C, $04, $D0, $D1, $D2, $D3, $2A, $7C, $82, $D4, $D6, $00

PRG025_CDA6:
	.byte $2A, $7F, $85, $D5 ; $CD9A - $CDA9
	.byte $D7, $D7, $D7, $D7, $2A, $BA, $04, $D0, $D1, $D2, $D3, $2A, $DA, $82, $D4, $D6 ; $CDAA - $CDB9
	.byte $00

PRG025_CDBB:
	.byte $2A, $80, $03, $D1, $D2, $D3, $2A, $A2, $01, $D5, $2A, $C1, $04, $D0, $D1 ; $CDBA - $CDC9
	.byte $D2, $D3, $2A, $E4, $01, $D5, $00

PRG025_CDD1:
	.byte $2B, $D1, $04, $55, $55, $55, $99, $2B, $D9 ; $CDCA - $CDD9
	.byte $04, $55, $55, $7F, $BB, $2B, $E1, $04, $A5, $A5, $AF, $AB, $00

PRG025_CDE7:
	.byte $28, $E3, $07 ; $CDDA - $CDE9
	.byte $DE, $F4, $EF, $F1, $E3, $5C, $78, $29, $24, $06, $E3, $E4, $F8, $E4, $EF, $F9 ; $CDEA - $CDF9
	.byte $29, $67, $04, $F1, $E0, $F3, $E3, $00

PRG025_CE02:
	.byte $2A, $65, $01, $58, $2A, $82, $05, $58 ; $CDFA - $CE09
	.byte $5C, $57, $5C, $56, $2A, $A1, $07, $57, $5C, $5A, $5C, $5C, $5C, $56, $00

PRG025_CE19:
	.byte $2A ; $CE0A - $CE19
	.byte $C0, $03, $57, $5C, $57, $2A, $C8, $01, $56, $2A, $E1, $01, $57, $2A, $E9, $01 ; $CE1A - $CE29
	.byte $56, $00, $00

PRG025_CE2D:
	.byte $2B, $CB, $04, $EA, $5A, $5A, $5A, $2B, $D3, $04, $66, $55, $55 ; $CE2A - $CE39
	.byte $55, $2B, $DB, $04, $66, $55, $55, $55, $00

PRG025_CE43:
	.byte $29, $A2, $05, $DE, $F4, $EF, $F1 ; $CE3A - $CE49
	.byte $E3, $29, $E4, $01, $79, $2A, $9A, $04, $CA, $CB, $CC, $CD, $00

PRG025_CE57:
	.byte $2A, $BA, $04 ; $CE4A - $CE59
	.byte $DA, $DB, $DC, $DD, $2A, $DA, $04, $CE, $CF, $5C, $DF, $2A, $FA, $04, $CE, $CF ; $CE5A - $CE69
	.byte $5C, $DF, $00

PRG025_CE6D:
	.byte $2A, $89, $0A, $DE, $E0, $F9, $E4, $EF, $5C, $F1, $E0, $F3, $E3 ; $CE6A - $CE79
	.byte $00

PRG025_CE7B:
	.byte $2B, $D2, $04, $E6, $FF, $FF, $FF, $2B, $DA, $04, $EE, $FF, $FF, $FF, $2B ; $CE7A - $CE89
	.byte $E2, $04, $AE, $AF, $AF, $AF, $00

PRG025_CE91:
	.byte $29, $78, $05, $DE, $F4, $EF, $F1, $E3, $29 ; $CE8A - $CE99
	.byte $BA, $01, $7A, $00

PRG025_CE9E:
	.byte $2A, $19, $05, $E8, $EA, $E0, $F3, $F9, $2A, $59, $04, $F1 ; $CE9A - $CEA9
	.byte $E0, $F3, $E3, $00

PRG025_CEAE:
	.byte $2B, $DA, $04, $FF, $FF, $FF, $BB, $00

PRG025_CEB6:
	.byte $2B, $E2, $04, $FF ; $CEAA - $CEB9
	.byte $FF, $FF, $BB, $2B, $EA, $04, $AF, $AF, $AF, $AB, $00

PRG025_CEC5:
	.byte $28, $F6, $07, $DE, $F4 ; $CEBA - $CEC9
	.byte $EF, $F1, $E3, $5C, $7B, $29, $36, $08, $F8, $F0, $FE, $5C, $F1, $E0, $F3, $E3 ; $CECA - $CED9
	.byte $28, $D0, $04, $C0, $C1, $C2, $C3, $00

PRG025_CEE2:
	.byte $28, $F0, $04, $C4, $C5, $C6, $C7, $29 ; $CEDA - $CEE9
	.byte $99, $04, $C0, $C1, $C2, $C3, $29, $B9, $04, $C4, $C5, $C6, $C7, $2A, $F9, $04 ; $CEEA - $CEF9
	.byte $D0, $D1, $D2, $D3, $00

PRG025_CEFF:
	.byte $28, $F6, $07, $DE, $F4, $EF, $F1, $E3, $5C, $7B, $00 ; $CEFA - $CF09

PRG025_CF0A:
	.byte $2B, $D1, $04, $5A, $FA, $FA, $9A, $2B, $D9, $04, $FF, $7F, $5F, $99, $2B, $E1 ; $CF0A - $CF19
	.byte $04, $55, $55, $55, $99, $00

PRG025_CF20:
	.byte $28, $E3, $07, $DE, $F4, $EF, $F1, $E3, $5C, $7C ; $CF1A - $CF29
	.byte $2A, $51, $08, $EA, $E2, $E4, $5C, $F1, $E0, $F3, $E3, $2A, $20, $0A, $01, $0D ; $CF2A - $CF39
	.byte $01, $0D, $01, $0D, $01, $0D, $01, $0D, $00

PRG025_CF43:
	.byte $2A, $40, $0A, $40, $4D, $40, $4D ; $CF3A - $CF49
	.byte $40, $4D, $40, $4D, $40, $4D, $2A, $60, $0A, $01, $0D, $01, $0D, $01, $0D, $01 ; $CF4A - $CF59
	.byte $0D, $01, $0D, $2A, $80, $0A, $40, $4D, $40, $4D, $40, $4D, $40, $4D, $40, $4D ; $CF5A - $CF69
	.byte $00

PRG025_CF6B:
	.byte $2A, $A0, $0C, $01, $0D, $01, $0D, $01, $0D, $01, $0D, $01, $0D, $01, $0D ; $CF6A - $CF79
	.byte $2A, $C0, $0C, $40, $4D, $40, $4D, $40, $4D, $40, $4D, $40, $4D, $40, $4D, $00 ; $CF7A - $CF89

PRG025_CF8A:
	.byte $2A, $E0, $10, $D8, $C9, $D8, $C9, $D8, $C9, $D8, $C9, $D8, $C9, $D8, $C9, $D8 ; $CF8A - $CF99
	.byte $C9, $D8, $C9, $00

PRG025_CF9E:
	.byte $2A, $F0, $10, $D8, $C9, $D8, $C9, $D8, $C9, $D8, $C9, $D8 ; $CF9A - $CFA9
	.byte $C9, $D8, $C9, $D8, $C9, $D8, $C9, $00

PRG025_CFB2:
	.byte $2B, $CB, $04, $EA, $FA, $FA, $FA, $2B ; $CFAA - $CFB9
	.byte $D3, $04, $EE, $7F, $FF, $FF, $2B, $DB, $04, $EE, $FF, $FF, $FF, $00

PRG025_CFC8:
	.byte $2A, $43 ; $CFBA - $CFC9
	.byte $07, $DE, $F4, $EF, $F1, $E3, $5C, $7D, $2A, $84, $09, $F5, $EA, $F5, $E4, $5C ; $CFCA - $CFD9
	.byte $F1, $E0, $F3, $E3, $29, $9A, $04, $CA, $CB, $CC, $CD, $29, $BA, $04, $DA, $DB ; $CFDA - $CFE9
	.byte $DC, $DD, $00

PRG025_CFED:
	.byte $29, $DA, $CA, $CE, $29, $DB, $CA, $CF, $00

PRG025_CFF6:
	.byte $29, $DD, $CA, $DF ; $CFEA - $CFF9
	.byte $2A, $74, $04, $CA, $CB, $CC, $CD, $2A, $94, $04, $DA, $DB, $DC, $DD, $00

PRG025_D009:
	.byte $2A ; $CFFA - $D009
	.byte $B4, $04, $CE, $CF, $5C, $DF, $2A, $D4, $04, $CE, $CF, $5C, $DF, $2A, $F4, $04 ; $D00A - $D019
	.byte $CE, $CF, $5C, $DF, $00

PRG025_D01F:
	.byte $2B, $C9, $04, $FA, $FA, $FA, $BA, $2B, $D1, $04, $FF ; $D01A - $D029
	.byte $FF, $FF, $BB, $2B, $D9, $04, $FF, $FF, $FF, $BB, $00

PRG025_D035:
	.byte $29, $63, $04, $E3, $E0 ; $D02A - $D039
	.byte $EF, $F0, $29, $A3, $04, $F1, $E0, $F3, $E3, $00

PRG025_D044:
	.byte $29, $7A, $05, $DE, $F4, $EF ; $D03A - $D049
	.byte $F1, $E3, $29, $9C, $01, $7E, $00

PRG025_D051:
	.byte $2B, $CA, $04, $6A, $5A, $5A, $5A, $00

PRG025_D059:
	.byte $2B ; $D04A - $D059
	.byte $D2, $04, $66, $55, $55, $55, $2B, $DA, $04, $66, $55, $55, $55, $00

EndSeq_World1Pal:
        vaddr $3F00
	.byte $20, $0F, $0F, $30, $16, $0F, $17, $2A, $37, $0F, $2C, $30, $37, $0F, $2C, $2A
	.byte $37, $0F, $16, $36, $0F, $0F, $0F, $30, $16, $0F, $0F, $30, $16, $0F, $0F, $30
	.byte $16

	; Terminator
	.byte $00

EndSeq_World2Pal:
        vaddr $3F00
	.byte $20, $0F, $0F, $30, $16, $0F, $17, $2A, $37, $0F, $2C, $30, $37, $0F, $2C, $2A
	.byte $37, $0F, $16, $36, $0F, $0F, $0F, $30, $16, $0F, $0F, $30, $2A, $0F, $0F, $30
	.byte $2A

	; Terminator
	.byte $00

EndSeq_World3Pal:
        vaddr $3F00
	.byte $20, $0F, $0F, $30, $16, $0F, $17, $2A, $37, $0F, $2C, $30, $37, $0F, $2C, $2A
	.byte $37, $0F, $2A, $36, $0F, $0F, $0F, $30, $16, $0F, $0F, $30, $16, $0F, $0F, $30
	.byte $16

	; Terminator
	.byte $00

EndSeq_World4Pal:
        vaddr $3F00
	.byte $20, $0F, $0F, $30, $16, $0F, $17, $2A, $37, $0F, $2C, $30, $37, $0F, $2C, $2A
	.byte $3A, $0F, $0F, $30, $16, $0F, $0F, $30, $16, $0F, $0F, $30, $16, $0F, $0F, $30
	.byte $16

	; Terminator
	.byte $00

EndSeq_World5Pal:
        vaddr $3F00
	.byte $20, $0F, $0F, $30, $16, $0F, $17, $2A, $30, $0F, $2C, $30, $37, $0F, $2C, $30
	.byte $30, $0F, $17, $36, $0F, $0F, $0F, $00, $10, $0F, $0F, $30, $26, $0F, $0F, $30
	.byte $16

	; Terminator
	.byte $00

EndSeq_World6Pal:
        vaddr $3F00
	.byte $20, $0F, $0F, $30, $16, $0F, $17, $2A, $30, $0F, $2C, $30, $37, $0F, $2C, $30
	.byte $30, $0F, $16, $36, $0F, $0F, $0F, $30, $16, $0F, $0F, $30, $2A, $0F, $0F, $30
	.byte $2A

	; Terminator
	.byte $00

EndSeq_World7Pal:
        vaddr $3F00
	.byte $20, $0F, $0F, $30, $16, $0F, $17, $2A, $37, $0F, $2C, $30, $37, $0F, $2C, $2A
	.byte $3A, $0F, $30, $36, $0F, $0F, $0F, $21, $2A, $0F, $0F, $30, $16, $0F, $0F, $30
	.byte $16

	; Terminator
	.byte $00

EndSeq_World8Pal:
        vaddr $3F00
	.byte $20, $0F, $0F, $30, $16, $0F, $17, $2A, $37, $0F, $2C, $30, $37, $0F, $2C, $2A
	.byte $37, $0F, $16, $36, $0F, $0F, $0F, $30, $0B, $0F, $0F, $30, $16, $0F, $0F, $30
	.byte $16

	; Terminator
	.byte $00

EndSeq_PrincessChamber:
	vaddr $3F00
	.byte $20, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F
	.byte $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F
	.byte $0F

	vaddr $2BC0
	.byte $30, $00, $00, $00, $00, $00, $00, $00, $00, $00, $F0, $7F, $5F, $5F, $DF, $F0
	.byte $00, $FC, $57, $55, $55, $55, $55, $5D, $F3, $77, $55, $55, $55, $55, $55, $55
	.byte $DD, $77, $55, $55, $55, $55, $55, $55, $DD, $77, $55, $55, $55, $55, $55, $55
	.byte $DD

	vaddr $2888
	.byte $10, $68, $6A, $68, $6A, $68, $6A, $68, $6A, $68, $6A, $68, $6A, $68, $6A, $68, $6A

	vaddr $28A8
	.byte $10, $69, $6B, $69, $6B, $69, $6B, $69, $6B, $69, $6B, $69, $6B, $69, $6B, $69, $6B

	vaddr $28C4
	.byte $18, $68, $6A, $68, $6A, $68, $6A, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
	.byte $FF, $FF, $FF, $68, $6A, $68, $6A, $68, $6A

	vaddr $28E4
	.byte $18, $69, $6B, $69, $6B, $69, $6B, $99, $99, $99, $99, $99, $99, $99, $99, $99
	.byte $99, $99, $99, $69, $6B, $69, $6B, $69, $6B

	vaddr $2902
	.byte $1C, $68, $6A, $68, $6A, $FF, $FF, $FF, $FF, $99, $99, $99, $99, $99, $99, $99
	.byte $99, $99, $99, $99, $99, $FF, $FF, $FF, $FF, $68, $6A, $68, $6A

	vaddr $2922
	.byte $1C, $69, $6B, $69, $6B, $99, $99, $99, $99, $99, $99, $99, $99, $99, $99, $99
	.byte $99, $99, $99, $99, $99, $99, $99, $99, $99, $69, $6B, $69, $6B

	vaddr $2940
	.byte $20, $68, $6A, $68, $6A, $FF, $FF, $99, $99, $99, $99, $99, $99, $99, $99, $99
	.byte $99, $99, $99, $99, $99, $99, $99, $99, $99, $99, $99, $FF, $FF, $68, $6A, $68
	.byte $6A

	vaddr $2960
	.byte $04, $69, $6B, $69, $6B

	vaddr $2964
	.byte VU_REPEAT | $18, $99

	vaddr $297C
	.byte $04, $69, $6B, $69, $6B

	vaddr $2980
	.byte $04, $68, $6A, $FF, $FF

	vaddr $2984
	.byte VU_REPEAT | $18, $99

	vaddr $299C
	.byte $04, $FF, $FF, $68, $6A

	vaddr $29A0
	.byte $02, $69, $6B

	vaddr $29A2
	.byte VU_REPEAT | $1B, $99

	vaddr $29BD
	.byte $03, $FF, $69, $6B

	vaddr $29C0
	.byte $02, $68, $6A

	vaddr $29C2
	.byte VU_REPEAT | $1B, $99

	vaddr $29DD
	.byte $03, $FF, $68, $6A

	vaddr $29E0
	.byte $02, $69, $6B

	vaddr $29E2
	.byte VU_REPEAT | $1B, $99

	vaddr $29FD
	.byte $03, $FF, $69, $6B

	vaddr $2A00
	.byte $02, $68, $6A

	vaddr $2A02

	.byte VU_REPEAT | $1B, $99

	vaddr $2A1D
	.byte $03, $FF, $68, $6A

	vaddr $2A20
	.byte $02, $69, $6B

	vaddr $2A22
	.byte VU_REPEAT | $1B, $99

	vaddr $2A3D
	.byte $03, $FF, $69, $6B

	vaddr $2A40
	.byte $02, $68, $6A

	vaddr $2A42
	.byte VU_REPEAT | $1B, $99

	vaddr $2A5D
	.byte $03, $FF, $68, $6A

	vaddr $2A60
	.byte $02, $69, $6B

	vaddr $2A62
	.byte VU_REPEAT | $1B, $99

	vaddr $2A7D
	.byte $03, $FF, $69, $6B

	vaddr $2A80
	.byte $02, $68, $6A

	vaddr $2A82
	.byte VU_REPEAT | $1B, $99

	vaddr $2A84
	.byte VU_REPEAT | $02, $FF

	vaddr $2A9D
	.byte $03, $FF, $68, $6A

	vaddr $2AA0
	.byte $02, $69, $6B

	vaddr $2AA2
	.byte VU_REPEAT | $1B, $99

	vaddr $2AA4
	.byte VU_REPEAT | $02, $FF

	vaddr $2ABD
	.byte $03, $FF, $69, $6B

	vaddr $2AC0
	.byte $02, $68, $6A

	vaddr $2AC2
	.byte VU_REPEAT | $1B, $99

	vaddr $2AC4
	.byte VU_REPEAT | $02, $FF
	
	vaddr $2ADD
	.byte $03, $FF, $68, $6A

	vaddr $2AE0
	.byte $02, $69, $6B

	vaddr $2AE2
	.byte VU_REPEAT | $1B, $99

	vaddr $2AE4
	.byte VU_REPEAT | $02, $FF

	vaddr $2AFD
	.byte $03, $FF, $69, $6B

	vaddr $2B00
	.byte $20, $62, $62, $63, $63, $62, $62, $63, $63, $62, $62, $63, $63, $62, $62, $63
	.byte $63, $62, $62, $63, $63, $62, $62, $63, $63, $62, $62, $63, $63, $62, $62, $63
	.byte $63

	vaddr $2B20
	.byte $20, $FD, $FD, $FC, $FC, $FD, $FD, $FC, $FC, $FD, $FD, $FC, $FC, $FD, $FD, $FC
	.byte $FC, $FD, $FD, $FC, $FC, $FD, $FD, $FC, $FC, $FD, $FD, $FC, $FC, $FD, $FD, $FC
	.byte $FC

	vaddr $2B40
	.byte $20, $FC, $FC, $FD, $FD, $FC, $FC, $FD, $FD, $FC, $FC, $FD, $FD, $FC, $FC, $FD
	.byte $FD, $FC, $FC, $FD, $FD, $FC, $FC, $FD, $FD, $FC, $FC, $FD, $FD, $FC, $FC, $FD
	.byte $FD

	vaddr $2B60
	.byte $20, $FC, $FC, $FD, $FD, $FC, $FC, $FD, $FD, $FC, $FC, $FD, $FD, $FC, $FC, $FD
	.byte $FD, $FC, $FC, $FD, $FD, $FC, $FC, $FD, $FD, $FC, $FC, $FD, $FD, $FC, $FC, $FD
	.byte $FD

	; Terminator
	.byte $00

EndSeq_Fade4:
	vaddr $3F00
	.byte $20, $0F, $0F, $30, $3C, $0F, $0C, $1C, $3B, $0F, $27, $30, $17, $0F, $12, $31
	.byte $21, $0F, $16, $36, $0F, $0F, $36, $25, $07, $0F, $2A, $36, $0F, $0F, $00, $00, $00

	; Terminator
	.byte $00

EndSeq_Fade3:
	vaddr $3F00
	.byte $20, $0F, $0F, $20, $2C, $0F, $0F, $0C, $2B, $0F, $17, $20, $07, $0F, $02, $21
	.byte $11, $0F, $06, $26, $0F, $0F, $26, $15, $0F, $0F, $1A, $26, $0F, $0F, $0F, $0F, $0F

	; Terminator
	.byte $00

EndSeq_Fade2:
	vaddr $3F00
	.byte $20, $0F, $0F, $10, $1C, $0F, $0F, $0F, $1B, $0F, $07, $10, $0F, $0F, $0F, $11
	.byte $01, $0F, $0F, $16, $0F, $0F, $16, $05, $0F, $0F, $0A, $16, $0F, $0F, $0F, $0F, $0F

	; Terminator
	.byte $00

EndSeq_Fade1:
	vaddr $3F00
	.byte $20, $0F, $0F, $00, $0C, $0F, $0F, $0F, $0B, $0F, $0F, $00, $0F, $0F, $0F, $01
	.byte $0F, $0F, $0F, $06, $0F, $0F, $06, $0F, $0F, $0F, $0F, $06, $0F, $0F, $0F, $0F, $0F

	; Terminator
	.byte $00

EndSeq_Fade0:
	vaddr $3F00
	.byte $20, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F
	.byte $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F

	; Terminator
	.byte $00

PRG025_D4B5:
        vaddr $3F10
	.byte $10, $0F, $21, $30, $0F, $0F, $11, $10, $0F, $0F, $12, $00, $0F, $0F, $0C, $0F
	.byte $0F

	; Terminator
	.byte $00

EndSeq_CurtainFadeIn1:
        vaddr $3F00
	.byte $10, $0F, $0F, $00, $06, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F
	.byte $0F

	; Terminator
	.byte $00


EndSeq_CurtainFadeIn2:
        vaddr $3F00
	.byte $10, $0F, $0F, $10, $16, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F
	.byte $0F

	; Terminator
	.byte $00


EndSeq_CurtainFadeIn3: 
       vaddr $3F00
	.byte $10, $0F, $0F, $20, $16, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F
	.byte $0F

	; Terminator
	.byte $00

PRG025_D505:
        vaddr $3F00
	.byte $10, $0F, $0F, $30, $16, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F
	.byte $0F

	; Terminator
	.byte $00


; Rest of ROM bank was empty

